### PR TITLE
upgrade scala 2.12

### LINKED ISSUE #1736: remove 2.12 monkey
sbt-ensime now (well, in a few hours) supports the 2.12.2 feature natively, so we can remove our monkey when it lands.

### PR DESCRIPTION
**Pull request by fommil**
close #1736

### CODE REVIEW

**Comment by fommil** [comment]
@som-snytt I got a few false positives in this when enabling `implicits` and `privates` unused warnings that you may be interested in, especially the `implicits` one.

**Comment by som-snytt** [comment]
Thanks I'll take a shot. I might need a few shots, thanks. Line 'em up.

**Comment by fommil** [comment]
interesting, the cleanups have somehow broken the `EnsimeConfigSpec`

**Comment by fommil** [comment]
the ClassfileIndexer is just full of unused parameter warnings, I couldn't be bothered. it can be picked up later when we are able to enable all linters.

**Comment by fommil** [comment]
@som-snytt another fun false positive for you... when enabling the `parameters` one we get a bunch of warnings in one file. If I add `@deprecating("local", "")` everywhere it needs it, I get a deprecation warning :crying_cat_face: this is in java bridge code, so it's not very pretty.

**Pull request merged**
