### PR TITLE
SNAPSHOT scala-refactoring

### LINKED ISSUE #1305: upgrade to scala-refactoring nightlies / next release
The moment when the dependency to scala-refactoring is updated one will get compilation errors because `PimpedTrees` does no longer exist. For now the change is not yet necessary since ensime-server doesn't depend on the nightlies of scala-refactoring.

The scala-refactoring change responsible for this issue can be found here: https://github.com/scala-ide/scala-refactoring/pull/135

### PR DESCRIPTION
**Pull request by fommil**
close #1305

### CODE REVIEW

**Comment by fommil** [comment]
@sshaef @mlangc this is looking good! We're a little cautious about depending on snapshots in case anything breaks, do you know how long it will be before 0.9.0 is released to central?

**Comment by fommil** [comment]
interesting, our CI jobs are not able to see the SNAPSHOT.

**Comment by sschaef** [comment]
probably one to two weeks. We are planning a new scala-ide+scala-refactoring release at the end of the month.

**Comment by fommil** [comment]
any ideas why we can't see the snapshots from our CI? I can see them locally.

**Comment by sschaef** [comment]
The sbt build still references the last release of scala-refactoring.

**Comment by fommil** [comment]
Doh! Bad merge. I'll fix now

**Comment by sschaef** [comment]
Man, did anyone already tell you that your build bot is slow? Even the Scala bot is faster and I thought so far this one is slow.

**Comment by fommil** [comment]
Heh, it had a lot of work to do last night. Our machines are not very powerful.

**Pull request merged**
