### PR TITLE
Fix a couple bugs in Java unsaved file flow.

### PR DESCRIPTION
**Pull request by aemoncannon**

### CODE REVIEW

**Comment by fommil** [comment]
You really love these unsaved files!

**Comment by fommil** [comment]
Looks like a real failure on `Starting test: 'Test misc operations on unsaved source file.'`

Now that the emacs tests have really stabilised, we should probably look to reduce the logging levels to just the test name and the failure message.

**Comment by aemoncannon** [comment]
Looks like a dumb mistake I put in ensime-emacs. Odd that tests didn't catch it..
PR'ed over there, and then will poke this branch to rebuild.

**Comment by aemoncannon** [comment]
Hah, yeah I'm obsessed with unsaved files! I feel like it's something new users would hit a lot. Or I'm just putting off doing important java stuff ;-)

**Comment by aemoncannon** [comment]
Is there any way to poke drone to re-check without pushing change?

**Comment by fommil** [comment]
@aemoncannon yeah, just log in and click the restart button. It ignores you if you don't go to fommil.com and login. The authors know about the bug.

**Pull request merged**
