### PR TITLE
Actorize ClassfileWatcher

### PR DESCRIPTION
**Pull request by lukasz-golebiewski**
Prerequisite for #1089

### CODE REVIEW

**Comment by fommil** [comment]
this keeps running out of memory. I'm starting to suspect that this is not a problem with our CI because a few other builds went through. Can you think of any memory leaks that you might have introduced?

**Comment by fommil** [comment]
@chipsenkbeil I've checked the logs and all the builds for this are running on your machine, e.g. http://fommil.com/ensime/ensime-server/193 can you please check that your dockers are definitely able to give up to 8GB of RAM?

**Comment by fommil** [comment]
yeah, more

```
[error] Uncaught exception when running org.ensime.core.SemanticHighlightingSpec: java.lang.OutOfMemoryError: unable to create new native thread
```

@lukasz-golebiewski can you have a think about this please?

**Comment by lukasz-golebiewski** [comment]
Sure, I'll have a look

**Comment by chipsenkbeil** [comment]
@fommil so I can see one container actively running right now on my machine related to ensime.

screen shot 2016-02-21 at 1 18 45 pm
screen shot 2016-02-21 at 1 19 20 pm

I do see the OutOfMemory exception in the logs, but I'm being told that the container has access to nearly 16 GB of RAM. Is there something I need to provide to the Docker daemon to allow it to use that much memory? I haven't done anything to it; so, I assumed that it already has access to available memory.

**Comment by fommil** [comment]
@chipsenkbeil we still haven't isolated if its your box or the code itself. From the look of that chart, it does seem like it shouldn't have a memory problem :-/

**Comment by chipsenkbeil** [comment]
I also executed `docker exec -it ensime-container-name /bin/bash`, installed the free program via `apt-get install procps`, and then ran `free -mh`:

screen shot 2016-02-21 at 1 29 32 pm

**Comment by fommil** [comment]
thanks for looking into this @chipsenkbeil ! Where do you get your machine hosting from? I'd like to use that instead of contabo.

**Comment by lukasz-golebiewski** [comment]
I executed the `it:test`s on my machine several times on `master` and on this branch. The memory usage never went above 800 MB and the number of live threads never exceeded 40. Peculiar

**Comment by fommil** [comment]
oh, but we fork all our tests... this is just the compiler process.

**Comment by lukasz-golebiewski** [comment]
Right, I'll investigate further tomorrow

**Comment by fommil** [comment]
yeah, I'm pretty confident this has introduced a regression. There have been tonnes of other tests today and none are exhibiting the same problem.

I honestly can't see the bug though.

**Comment by lukasz-golebiewski** [comment]
Tests for this PR were successful one time: http://fommil.com/ensime/ensime-server/191
Is it possible that other tests were executed on other worker nodes on which the problems do not occur? Could we trigger a build of `master` on the one that's failing? I'm just guessing here, as I also cannot see the error - the new Actor should be destroyed along with it's parent and the resources should be freed.

**Comment by fommil** [comment]
yeah, it's altogether very confusing.

**Comment by fommil** [comment]
ok, definitely a docker problem. I just seen this on a totally unrelated build http://fommil.com/ensime/ensime-server/212/1

**Comment by fommil** [comment]
@chipsenkbeil I'm taking your machine off the network for a bit, we should investigate what is going on

**Comment by chipsenkbeil** [comment]
@fommil okay, let me know what you need done to help figure out this problem. I'm not seeing anything obvious on my end in terms of memory usage, just that the exception is thrown.

**Comment by fommil** [comment]
I actually don't know how to fix it, but I suspect it'll be something to do with docker version / system config? fyi we're on `docker --version ; Docker version 1.10.1, build 9e83765`

**Comment by chipsenkbeil** [comment]
Same build for me. I'll send you my docker.service file privately on Gitter.

**Comment by fommil** [comment]
@lukasz-golebiewski sorry to leave you hanging on this one. Can you please rebase and squash your commits?

**Comment by lukasz-golebiewski** [comment]
@fommil Done

**Pull request merged**
