### PR TITLE
Fixed not working git grep in .drone.yml

### PR DESCRIPTION
**Pull request by asznajder**
Unfortunately, drone doesn't understand magic paths (`!` for `:(exclude)`) in `git grep`. That's why #1403 showed us that #1400 doesn't really work and needs a fix. That's why, we changed _.drone.yml_ to use the unix `grep` instead of path exclusion. 

Extra: Prettier `git diff` in `.drone_yml` (no more lines counting to find diffs).

### CODE REVIEW

**Comment by fommil** [comment]
ok cool, so we'll see if this goes green and then add a commit which demonstrates TODO breaking the build, then back it out and add another commit showing code formatting also breaking the build, then back that out, then I'll squash merge.

**Comment by fommil** [comment]
@asznajder ok, that was green. Now add a commit with a TODO in it and we'll see it go RED.

**Comment by asznajder** [comment]
Yay! It's red ;)

**Comment by fommil** [comment]
nice! OK, now add a commit that reverts this change and introduces some alternative formatting in a random scala file. It should be red also.

**Comment by asznajder** [comment]
Looks like working

**Comment by fommil** [comment]
cool! Add a commit that reverts the formatting change and I think this is good for merge.

**Comment by fommil** [comment]
oh I just realised you created a fresh PR for this. You could have continued on the original PR.

Thanks!

**Pull request merged**
