### PR TITLE
Fix symbol at point at beginning of word for Java

### PR DESCRIPTION
**Pull request by tanzoniteblack**
Fixes https://github.com/ensime/ensime-server/issues/1199

Also: Adds testing for symbol at point at both beginning and end of
symbol, though the fix only addresses the beginning of symbol issue.

### CODE REVIEW

**Comment by tanzoniteblack** [comment]
My emacs config automatically removed a bunch of extraneous whitespace in that java file as well, you can view the changes without the whitespace changes with https://github.com/ensime/ensime-server/pull/1202/files?w=1 . If it's a big issue, let me know and I'll go back and try to remake the diff without them.

**Comment by aemoncannon** [comment]
Awesome!
Please do nix the ws changes.
Also, please add tests for single char symbol.

**Comment by tanzoniteblack** [comment]
@aemoncannon added the tests for the single char symbol.

And if the source code could be cleaned up at some point in the future to not have spurious, random whitespace, it would make it easier to have meaningful diffs in the future. To make this PR easier I've gone ahead and cleaned up the whitespace changes for now.

**Comment by fommil** [comment]
yeah, we need to have the equivalent of a scalariform for java, to enforce the formatting.

**Comment by fommil** [comment]
can you please squash all commits into one? Helps with bisecting.

**Comment by aemoncannon** [comment]
needs a rebase now (sorry for that)
other than that, lgtm
thanks!

**Comment by tanzoniteblack** [comment]
Rebased

**Comment by aemoncannon** [comment]
Merged. Thanks for the great fix!

**Pull request merged**
