### PR TITLE
Show transient inheritors as well

### PR DESCRIPTION
**Pull request by VC1995**
#1854

### CODE REVIEW

**Comment by VC1995** [comment]
Is this what we want?
Should i add a test?

**Comment by fommil** [comment]
a test would be great!

**Comment by fommil** [comment]
It's this still WIP? looks done to me

**Comment by VC1995** [comment]
Yep, it's done. Had to wait till the weekend for adding the test.

**Comment by fommil** [comment]
Awesome. I'll merge this as soon as it goes green. Could you please update the title?

**Pull request merged**
