### PR TITLE
Stray code fix jar urls

### PR DESCRIPTION
**Pull request by hardmettle**
@fommil I have implemented the missing pieces leftover from jar-urls. Please take a look .

### CODE REVIEW

**Comment by fommil** [comment]
Cool! But you have build failures

**Comment by hardmettle** [comment]
@fommil I think it's because of the indentation ?

**Comment by fommil** [comment]
you need to run `sbt test:compile it:compile` before committing to ensure that the auto formatter runs.

**Comment by hardmettle** [comment]
@fommil Can you restart the appveyor integration? I cant find any issues with the test which failed on appveyor.

**Comment by fommil** [comment]
done

**Comment by fommil** [comment]
thanks again!

**Pull request merged**
