### PR TITLE
fixup 1344

### LINKED ISSUE #692: loose ends in S-Express
* SexpData unapply should allow dupes, on a first key wins basis
* SexpList apply should have a tail recursive instead of recurse that could blow up the stack
* ensure that Either/Option have alternative handlers (be strict by default, but allow the lazier "common sense" form)

### PR DESCRIPTION
**Pull request by fommil**
cleanup #1344 which closes #692

### CODE REVIEW

**Comment by fommil** [comment]
drone failure is transient

**Comment by aemoncannon** [comment]
Quick question: does the nil skipping also skip empty list?

**Comment by aemoncannon** [comment]
That is, does it omit a key if the key's value is an empty sexplist? (I'm hoping it does).

**Comment by aemoncannon** [comment]
That can actually save a lot of traffic.

**Comment by fommil** [comment]
Yep, but it's not enabled by default yet.

**Comment by fommil** [comment]
I'll see if its easy to update this...

**Comment by fommil** [comment]
looking easy, I'll raise a PR after my dinner (only time I've been able to write any code today, hack day was insane. 8 new users and almost 5 PRs. wow)

**Pull request merged**
