### PR TITLE
recover original sexp package structure

### PR DESCRIPTION
**Pull request by fommil**
knocking something out quickly to test the PR builder

### CODE REVIEW

**Comment by fommil** [comment]
wtf, coverage dropped to 74.98% without me touching any code!

**Comment by fommil** [comment]
aah, I did remove code. I reverted an older version of one of the tests. Force pushed it.

**Comment by fommil** [comment]
self merging so that I can do a 2.10/2.9 backport in prep for eric's work

**Comment by rorygraves** [comment]
Cool

**Pull request merged**
