### PR TITLE
Index type aliases

### LINKED ISSUE #599: edit-definition fails for type aliases
e.g. on a `String`, the prescomp resolves it as `scala.Predef.String` and that fails index lookup (although `type` passes)... the response is therefore missing a `decl-as`.

Fix would be provided by using the depickler to get type alias definitions, or by working around it by falling back to the `pos` of the `type`.

```
[info] 16:29:21.982 [default-akka.actor.default-dispatcher-5] INFO  org.ensime.protocol.SwankProtocol - Received msg: (:swank-rpc (swank:symbol-at-point "/home/hallisam/ensime-server/src/main/scala/org/ensime/server/Completion.scala" 506) 5)
[info] 16:29:22.007 [Scala Presentation Compiler []] DEBUG o.e.server.RichPresentationCompiler - search: scala.Predef.String = None
[info] 16:29:22.073 [Scala Presentation Compiler []] DEBUG o.e.server.RichPresentationCompiler - search: java.lang.String = Some(FqnSymbol(Some(185595),file:///opt/jdk1.6.0_45/jre/lib/rt.jar,jar:file:///opt/jdk1.6.0_45/jre/lib/rt.jar!/java/lang/String.class,java.lang.String,None,None,Some(jar:file:///opt/jdk1.6.0_45/src.zip!/java/lang/String.java),Some(122),Some(4649)))
[info] 16:29:22.163 [default-akka.actor.default-dispatcher-5] INFO  org.ensime.protocol.SwankProtocol - Writing: (:return (:ok (:name "String" :local-name "String" :type (:name "String" :type-id 1 :full-name "java.lang.String" :decl-as class :pos (:file "/home/hallisam/ensime-server/.ensime_cache/dep-src/source-jars/java/lang/String.java" :offset 4649 :line 122)) :owner-type-id 2)) 5)
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/4466786-edit-definition-fails-for-type-aliases?utm_campaign=plugin&utm_content=tracker%2F239449&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F239449&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by edani**
This fixes #599.  To try out this change, delete .ensime_cache or force reindexing some other way.

### CODE REVIEW

**Comment by fommil** [comment]
:smile: yay! You're probably hit by all the build instability that's come along with integrating the emacs tests, I'll hopefully get to the bottom of that today.

I'll definitely be testing this tomorrow at work.

**Comment by rorygraves** [comment]
Looking at the error this looks like a real bug (or a nasty race).
```project.rpcPublicSymbolSearch(List("java", "io", "File"), 2)```
is picking up

``` scala.sys.process.processInternal$File``` as its first match, which seems unexpected.

**Comment by edani** [comment]
I'm seeing the error too, I'll look into it.

**Comment by fommil** [comment]
This might just be because we're not adding boosts to the index entries. I should really do something trivial for 1.0.

**Comment by fommil** [comment]
other than the failing test, this is working nicely! Change the test if you're happy that it's just poor indexing on my part. I'll look into this later on.

**Comment by edani** [comment]
I don't 100% understand the lucene search part, but it looks like it aggregates matches of one term at a time. So in the test, the search for "java" "io" "File" seems to weigh a match on just "File" as high as matching all three.   So I pushed a test change.

**Comment by fommil** [comment]
Oh yes, I remember that now... that's what I wanted to change

**Comment by rorygraves** [comment]
@edani - Needs a rebase - sorry

**Comment by fommil** [comment]
I kicked off another CI.

**Comment by fommil** [comment]
I'll check locally, if it passes, I'll merge

**Comment by fommil** [comment]
awesome stuff, as always, @edani :smile:

**Pull request merged**
