### PR TITLE
Slick 3.1

### PR DESCRIPTION
**Pull request by cvogt**
Cleaned up history. Ready to be merged.

### CODE REVIEW

**Comment by fommil** [comment]
I added quite a bit of `log.info` with the name of the currently running method, feel free to remove it... it's just noise now.

**Comment by cvogt** [comment]
So these commits are all good to be merged for me now, except locally, I get this failure for it:test

```
[info] - should open the pure Java test project *** FAILED ***
[info]   java.util.NoSuchElementException: head of empty list
[info]   at scala.collection.immutable.Nil$.head(List.scala:420)
[info]   at scala.collection.immutable.Nil$.head(List.scala:417)
[info]   at org.ensime.fixture.EnsimeConfigFixture$class.main(EnsimeConfigFixture.scala:24)
[info]   at org.ensime.intg.JavaWorkflow.main(JavaWorkflow.scala:10)
[info]   at org.ensime.fixture.EnsimeConfigFixture$class.javaMain(EnsimeConfigFixture.scala:29)
[info]   at org.ensime.intg.JavaWorkflow.javaMain(JavaWorkflow.scala:10)
[info]   at org.ensime.intg.JavaWorkflow$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$1$$anonfun$apply$2.apply(JavaWorkflow.scala:25)
[info]   at org.ensime.intg.JavaWorkflow$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$1$$anonfun$apply$2.apply(JavaWorkflow.scala:22)
[info]   at org.ensime.fixture.IsolatedProjectFixture$class.withProject(ProjectFixture.scala:64)
[info]   at org.ensime.intg.JavaWorkflow.withProject(JavaWorkflow.scala:10)
[info]   at org.ensime.intg.JavaWorkflow$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$1.apply(JavaWorkflow.scala:22)
[info]   at org.ensime.intg.JavaWorkflow$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$1.apply(JavaWorkflow.scala:21)
[info]   at org.ensime.fixture.IsolatedTestKitFixture$class.withTestKit(TestKitFixture.scala:39)
[info]   at org.ensime.intg.JavaWorkflow.withTestKit(JavaWorkflow.scala:10)
[info]   at org.ensime.intg.JavaWorkflow$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(JavaWorkflow.scala:21)
[info]   at org.ensime.intg.JavaWorkflow$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(JavaWorkflow.scala:20)
[info]   at org.ensime.fixture.IsolatedEnsimeConfigFixture$$anonfun$withEnsimeConfig$1.apply(EnsimeConfigFixture.scala:134)
[info]   at org.ensime.fixture.IsolatedEnsimeConfigFixture$$anonfun$withEnsimeConfig$1.apply(EnsimeConfigFixture.scala:134)
[info]   at org.ensime.util.file.package$.withTempDir(file.scala:43)
[info]   at org.ensime.fixture.IsolatedEnsimeConfigFixture$class.withEnsimeConfig(EnsimeConfigFixture.scala:133)
[info]   at org.ensime.intg.JavaWorkflow.withEnsimeConfig(JavaWorkflow.scala:10)
[info]   at org.ensime.intg.JavaWorkflow$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(JavaWorkflow.scala:20)
[info]   at org.ensime.intg.JavaWorkflow$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(JavaWorkflow.scala:20)
[info]   at org.ensime.intg.JavaWorkflow$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(JavaWorkflow.scala:20)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at org.scalatest.WordSpec.withFixture(WordSpec.scala:1881)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpec.runTest(WordSpec.scala:1881)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1424)
[info]   at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[info]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1067)
[info]   at org.scalatest.WordSpec.run(WordSpec.scala:1881)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:466)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:677)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:296)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:286)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:745)
```

**Comment by fommil** [comment]
have a read of the `.drone.yml` file to see what you need to do as prep. TL;DR run `sbt gen-ensime` first.

**Comment by cvogt** [comment]
alright, good to be merged for me

**Comment by fommil** [comment]
:fireworks:

**Comment by cvogt** [comment]
nice :)! Glad I could contribute something back.

**Comment by rorygraves** [comment]
Nice!

**Pull request merged**
