### PR TITLE
Change Licence to GPL

### PR DESCRIPTION
**Pull request by fommil**
Originally motivated by neo4j, it has turned out that this is generally seen as a positive move in any case. We only need approval from committers who have submitted significant portions to ENSIME:

- [x] @fommil
- [x] @aemoncannon
- [x] @rorygraves
- [x] @edani
- [x] @xeno-by

### CODE REVIEW

**Comment by edani** [comment]
OK with me.

**Comment by fommil** [comment]
LOL the windows build failed. How apt.

**Comment by fommil** [comment]
FYI I ran this script to be on the safe side which shows the latest people to touch each line for the current `HEAD` code, we'll take a few days to get everybody's feedback. It's not such a big deal if we don't because if somebody even disagreed, it is possible to include Apache 2.0 source code in a GPL project:

```
git ls-tree --name-only -z -r HEAD|egrep -z -Z -E '\.(scala|java)$'   |xargs -0 -n1 git blame -wCCC --line-porcelain|grep "^author "|sort|uniq -c|sort -nr
```

*  12982 author Sam Halliday @fommil
*   3406 author Aemon Cannon @aemoncannon 
*   2975 author Rory Graves @rorygraves 
*    877 author Eric Daniel @edani 
*    144 author hiroyuki nagata @Hiroyuki-Nagata
*    117 author Jan Christopher Vogt @cvogt
*    108 author Eric Sessoms @esessoms
*     93 author Alejandro Lopez @ale64bit 
*     52 author Trond Sandnes Bjerkestrand @tbje
*     39 author Eugene Burmako @xeno-by
*     25 author Scalariform (automated)
*     19 author Marc Saegesser @marcsaegesser 
*     16 author Alejandro Pedraza @alpeb 
*     14 author Jacob Schlather @jschlather 
*      7 author Dick Wall @dickwall 
*      1 author Pawel Kopiczko @kopiczko 
```

(btw, I'm pretty sure my line count is just because I've just moved stuff around a lot and made it look like I was working... I'm a Pro)

**Comment by fommil** [comment]
damn, I managed to break the emacs tests somehow in the other branch (this PR should be green)

**Comment by esessoms** [comment]
:+1: GPL

**Comment by cvogt** [comment]
no objections. +1

**Comment by fommil** [comment]
ok, I think we've hit critical mass... @aemoncannon the merge honour should be yours!

**Comment by ale64bit** [comment]
Just for the record, no objections here :)

**Comment by alpeb** [comment]
Fine by me :)

**Comment by Hiroyuki-Nagata** [comment]
no objection

**Comment by aemoncannon** [comment]
Commencing Gnu-ification in 10.. 9.. 8...

**Comment by rorygraves** [comment]
lol

**Comment by fommil** [comment]
Join us now and share the software, you'll be free!

**Comment by marcsaegesser** [comment]
This is fine with me.

Sorry for being late to the party again.

**Comment by tbje** [comment]
Fine by me.

man. 2. nov. 2015, 18.06 skrev Marc Saegesser <notifications@github.com>:

**Comment by dickwall** [comment]
OK, OK, I officially prostrate myself before the idolatry of Stallman :-)

Make it so, number one

**Pull request merged**
