### PR TITLE
Complete work on startup futures (again)

### PR DESCRIPTION
**Pull request by rorygraves**

### CODE REVIEW

**Comment by rorygraves** [comment]
@fommil Updated.

**Comment by fommil** [comment]
wtf, you push and the tests are finished EIGHT MINUTES later???? What is this, a Java project?

**Comment by rorygraves** [comment]
I can make it slower if you like :smiley:

**Comment by fommil** [comment]
@rorygraves heh, that's **my** job!

**Comment by rorygraves** [comment]
And with your use of implicits, what an incredible job you are doing...

**Comment by fommil** [comment]
:bow:

**Pull request merged**
