### PR TITLE
Refactor java fqn creation.

### PR DESCRIPTION
**Pull request by aemoncannon**
This lets us dramatically simplify / improve jump-to-decl and doc finding.
Yay!

### CODE REVIEW

**Comment by aemoncannon** [comment]
Booooo. Some work left to do to make this pass on Java 6. Something about getting Element for a local var identifier is borked. Will pick it up after the holiday.

**Comment by aemoncannon** [comment]
I finally installed all of 1.6,1.7,1.8 locally. Managed neatly by jenv on osx. Turns out these issues are actually 1.6 and 1.7, not just 1.6 like I've been assuming. Anyway now that I can repro locally should be much easier to fix things.

**Comment by fommil** [comment]
I use .sbtopts the force the Java home for each SBT project.

**Comment by aemoncannon** [comment]
Getting closer, with some dirty tricks. Even if tests pass, please don't merge yet. I want to clean up.

**Comment by aemoncannon** [comment]
Ok! Locally passing on 1.6, 1.7, 1.8. I isolated what's broken in 1.6, 1.7 and added a filthy workaround in UnsafeHelpers.

**Comment by aemoncannon** [comment]
Added testing for finding local var and param declaration positions, which come for free now.

**Comment by fommil** [comment]
cool, it's gone green. Squash and merge when you're happy with it, it looks good to me!

**Comment by fommil** [comment]
Hmm, it went red just before merging. Was that transient?

**Comment by fommil** [comment]
It is green out master, must be transient.

Now my turn to clean up FQN creation on the Scala side!

**Pull request merged**
