### PR TITLE
Rename rpcXXX methods to XXX in api

### PR DESCRIPTION
**Pull request by rorygraves**

### CODE REVIEW

**Comment by rorygraves** [comment]
I think the commit method and the changes are fairly self explainatory - basically this a small step on the Ensime as an api path.

**Comment by rorygraves** [comment]
@fommil  Any idea whats going on with Shippable/elpa?

**Comment by fommil** [comment]
@rorygraves yeah, they screwed up again https://github.com/Shippable/support/issues/1419

**Comment by rorygraves** [comment]
ok, that makes me feel a little better...

**Comment by fommil** [comment]
oh, but I think the emacs tests actually did time out this time.

**Pull request merged**
