### PR TITLE
moving things into their modules

### PR DESCRIPTION
**Pull request by fommil**

### CODE REVIEW

**Comment by fommil** [comment]
my permissions to see `ensime` in shippable just disappeared. WTF... https://github.com/Shippable/support/issues/1236

**Comment by fommil** [comment]
@rorygraves tag, you're it.

**Comment by fommil** [comment]
btw, @rorygraves, your jenkins box is running a bunch of tasks that are doomed to failure. Can you please disable the Jenkins jobs so that the cycles are freed up for Shippable builds?

**Comment by rorygraves** [comment]
Good point  - Jenkins jobs are gone.

**Comment by rorygraves** [comment]
@fommil  Whilst the devops side is important its nice to see you back in the code :)

**Pull request merged**
