### PR TITLE
Java7 tree api

### PR DESCRIPTION
**Pull request by mwielocha**
In theory this solved #1491 in practice this is mostly cosmetic, cause #1491 wash solved with natbeans removal.
To be honest nothing really interesting here 😸

### CODE REVIEW

**Comment by fommil** [comment]
LGTM

**Comment by aemoncannon** [comment]
Nice!

**Comment by fommil** [comment]
@aemoncannon is 1.0.0 working for you now on your big work project? Or will you have to wait for the graphpocalypse build?

**Comment by aemoncannon** [comment]
Last I tried it works quite well! My issues are more build-logistics at
this point -- build is slow, and I'm working on some tools to generate
ensime projects for subcomponents.

**Comment by fommil** [comment]
@aemoncannon awesome! Be sure to check out the workflow in sbt-big-project. No doubt you'll have to re-implement a lot of that for your build tool.

**Comment by mwielocha** [comment]
Yay!

**Pull request merged**
