### PR TITLE
Add protocol support for looking up a doc by fully qualified name.

### PR DESCRIPTION
**Pull request by aemoncannon**
See corresponding PR in ensime-emacs.
I may follow up with a PR to clean up the protocol a bit, as there are other places that accept different arguments to select a symbol.
May need tests. Let's see what coverage jerk says : )

### CODE REVIEW

**Comment by fommil** [comment]
Test jerk got there first :stuck_out_tongue: 

```
[error] Failed tests:
[error] 	org.ensime.server.protocol.swank.SwankProtocolSpec
```

**Comment by rorygraves** [comment]
Most people just call me Rory rather than 'coverage jerk' ;)

**Comment by rorygraves** [comment]
This is awesome stuff btw.

**Comment by aemoncannon** [comment]
Refactored to better support packages with [A-Z] characters. Added a test exercising this and javadoc 1.8 jars.

@fommil I rebased to the modularized master, and am now seeing lots of integrations failing (at least locally). Could you take a look (I probably just merged wrong or something..)?

**Comment by aemoncannon** [comment]
@fommil Fewer failing now...

**Comment by fommil** [comment]
You need to run gen-ensime for the tests to run now.

**Comment by fommil** [comment]
tests are failing because of the use of the scoverage javadoc. I don't see those in the dependency list. It's a weird `provided` dependency or something, so it isn't part of the `.ensime`

**Comment by fommil** [comment]
that green light for travis was a dangerous false positive... I found the cause (bug in sbt/scalatest integration), linked above. I have a PR to workaround it, it's trivial so I'll merge when it is ok.

**Comment by aemoncannon** [comment]
Fixed remaining failures (locally -- we'll see what travis says). Cleaned up "java" checks. Got rid of scalac-scoverage usage.

**Pull request merged**
