### PR TITLE
Add by-name parameter support to ArrowTypeInfoBuilder

### LINKED ISSUE #1477: TypeToScalaNameSpec should report ArrowType for by name parameters
1. add a test to `TypeToScalaNameSpec` for a by name method parameter
2. assert that it is an arrow type. By guess is that it reports as a `BasicType` right now

### PR DESCRIPTION
**Pull request by iravid**
This resolves #1477

### CODE REVIEW

**Comment by fommil** [comment]
This has broken the emacs integration tests.

It probably requires a small fix on the emacs side. Are you up to fixing that? grep the code for `<byname>` and you'll find it real easily.

**Comment by iravid** [comment]
Yeah, figured that was the issue :-) Looking into it.

**Comment by fommil** [comment]
remember the client has to support both protocols, so don't just change it... add support for both ways of writing a byname.

**Comment by iravid** [comment]
Oh. Wasn't aware of that backwards compatibility requirement.

**Comment by fommil** [comment]
I kicked off a build

**Comment by fommil** [comment]
LGTM, what's next on your hit list?

**Comment by fommil** [comment]
LGTM

**Pull request merged**
