### PR TITLE
Fix #1029

### LINKED ISSUE #1029: refactor import results in corrupted source code if the first line is an import statement
I executed a useful command `C-x C-r t` , but it sometimes fail its import.
In my case, I tried to import like below:
```
import org.scalatra._
import javax.servlet.ServletContext
import _root_.akka.actor.ActorSystem
import com.mordor.minas_morgul.Foo
import com.mordor.minas_morgul.Bar
import com.mordor.minas_morgul.Yahoo
```

...and, exec `C-x C-r t`, but it failed. `import` is bizarre.
```
iimport com.mordor.minas_morgul.Google
mport org.scalatra._
import javax.servlet.ServletContext
import _root_.akka.actor.ActorSystem
import com.mordor.minas_morgul.Foo
import com.mordor.minas_morgul.Bar
import com.mordor.minas_morgul.Yahoo
```

Logs are like below:
```
16:04:18.408 [default-akka.actor.default-dispatcher-38] INFO  o.e.s.protocol.swank.SwankProtocol - Received msg: (:swank-rpc (swank:typecheck-file (:file "/home/golumn/git_lotr_tools/lotr-strategy/src/main/scala/ScalatraBootstrap.scala" :contents "iimport com.mordor.servlet.Swagg\
 erServlet\nmport org.scalatra._\nimport javax.servlet.ServletContext\nimport _root_.akka.actor.ActorSystem\nimport com.mordor.dao.ConnectionInfoFactory\nimport com.mordor.statsd.StatsdClient\nimport com.mordor.lotr.strategy._\nimport com.mordor.lotr.strategy.service.{StrategyDisp\
 atchClient, Strateg...
 16:04:18.412 [default-akka.actor.default-dispatcher-48] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:clear-all-scala-notes)
 16:04:18.416 [Scala Presentation Compiler []] WARN  org.ensime.util.PresentationReporter - Unsupported operation during reporting
 java.lang.UnsupportedOperationException: Position.start on class scala.reflect.internal.util.OffsetPosition
         at scala.reflect.internal.util.Position.start(Position.scala:114) ~[scala-reflect-2.10.2.jar:na]
         at org.ensime.util.PresentationReporter.info0(Reporter.scala:42) ~[ensime_2.10.jar:0.9.10-SNAPSHOT]
         at scala.tools.nsc.reporters.Reporter$$anonfun$error$1.apply$mcV$sp(Reporter.scala:70) [scala-compiler-2.10.2.jar:na]
         at scala.tools.nsc.reporters.Reporter$$anonfun$error$1.apply(Reporter.scala:70) [scala-compiler-2.10.2.jar:na]
         at scala.tools.nsc.reporters.Reporter$$anonfun$error$1.apply(Reporter.scala:70) [scala-compiler-2.10.2.jar:na]
         at scala.tools.nsc.reporters.Reporter.withoutTruncating(Reporter.scala:42) [scala-compiler-2.10.2.jar:na]
         at scala.tools.nsc.reporters.Reporter.error(Reporter.scala:70) [scala-compiler-2.10.2.jar:na]
         at scala.tools.nsc.CompilationUnits$CompilationUnit.error(CompilationUnits.scala:102) [scala-compiler-2.10.2.jar:na]
         at scala.tools.nsc.ast.parser.Parsers$UnitParser$$anonfun$showSyntaxErrors$2.apply(Parsers.scala:226) [scala-compiler-2.10.2.jar:na]
         at scala.tools.nsc.ast.parser.Parsers$UnitParser$$anonfun$showSyntaxErrors$2.apply(Parsers.scala:225) [scala-compiler-2.10.2.jar:na]
         at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772) [scala-library-2.10.2.jar:na]
         at scala.collection.immutable.List.foreach(List.scala:318) [scala-library-2.10.2.jar:na]
         at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32) [scala-library-2.10.2.jar:na]
         at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45) [scala-library-2.10.2.jar:na]
         at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771) [scala-library-2.10.2.jar:na]
         at scala.tools.nsc.ast.parser.Parsers$UnitParser.showSyntaxErrors(Parsers.scala:225) [scala-compiler-2.10.2.jar:na]
         at scala.tools.nsc.ast.parser.Parsers$UnitParser.smartParse(Parsers.scala:242) [scala-compiler-2.10.2.jar:na]
         at scala.tools.nsc.ast.parser.SyntaxAnalyzer$ParserPhase.apply(SyntaxAnalyzer.scala:29) [scala-compiler-2.10.2.jar:na]
         at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:464) [scala-compiler-2.10.2.jar:na]
         at scala.tools.nsc.Global$Run$$anonfun$compileLate$2$$anonfun$apply$1.apply(Global.scala:1683) [scala-compiler-2.10.2.jar:na]
         at scala.tools.nsc.Global$Run$$anonfun$compileLate$2$$anonfun$apply$1.apply(Global.scala:1683) [scala-compiler-2.10.2.jar:na]
         at scala.reflect.internal.SymbolTable.atPhase(SymbolTable.scala:207) [scala-reflect-2.10.2.jar:na]
         at scala.tools.nsc.Global$Run$$anonfun$compileLate$2.apply(Global.scala:1683) [scala-compiler-2.10.2.jar:na]
         at scala.tools.nsc.Global$Run$$anonfun$compileLate$2.apply(Global.scala:1682) [scala-compiler-2.10.2.jar:na]
         at scala.collection.Iterator$class.foreach(Iterator.scala:727) [scala-library-2.10.2.jar:na]
         at scala.collection.AbstractIterator.foreach(Iterator.scala:1157) [scala-library-2.10.2.jar:na]
         at scala.tools.nsc.Global$Run.compileLate(Global.scala:1682) [scala-compiler-2.10.2.jar:na]
         at scala.tools.nsc.interactive.Global.scala$tools$nsc$interactive$Global$$parseAndEnter(Global.scala:573) [scala-compiler-2.10.2.jar:na]
         at scala.tools.nsc.interactive.Global.backgroundCompile(Global.scala:480) [scala-compiler-2.10.2.jar:na]
         at scala.tools.nsc.interactive.PresentationCompilerThread.run(PresentationCompilerThread.scala:25) [scala-compiler-2.10.2.jar:na]
 16:04:18.417 [Scala Presentation Compiler []] WARN  org.ensime.util.PresentationReporter - Unsupported operation during reporting
16:04:18.417 [Scala Presentation Compiler []] WARN  org.ensime.util.PresentationReporter - Unsupported operation during reporting
java.lang.UnsupportedOperationException: Position.start on class scala.reflect.internal.util.OffsetPosition
        at scala.reflect.internal.util.Position.start(Position.scala:114) ~[scala-reflect-2.10.2.jar:na]
        at org.ensime.util.PresentationReporter.info0(Reporter.scala:42) ~[ensime_2.10.jar:0.9.10-SNAPSHOT]
        at scala.tools.nsc.reporters.Reporter$$anonfun$error$1.apply$mcV$sp(Reporter.scala:70) [scala-compiler-2.10.2.jar:na]
        at scala.tools.nsc.reporters.Reporter$$anonfun$error$1.apply(Reporter.scala:70) [scala-compiler-2.10.2.jar:na]
        at scala.tools.nsc.reporters.Reporter$$anonfun$error$1.apply(Reporter.scala:70) [scala-compiler-2.10.2.jar:na]
        at scala.tools.nsc.reporters.Reporter.withoutTruncating(Reporter.scala:42) [scala-compiler-2.10.2.jar:na]
        at scala.tools.nsc.reporters.Reporter.error(Reporter.scala:70) [scala-compiler-2.10.2.jar:na]
        at scala.tools.nsc.CompilationUnits$CompilationUnit.error(CompilationUnits.scala:102) [scala-compiler-2.10.2.jar:na]
        at scala.tools.nsc.ast.parser.Parsers$UnitParser$$anonfun$showSyntaxErrors$2.apply(Parsers.scala:226) [scala-compiler-2.10.2.jar:na]
        at scala.tools.nsc.ast.parser.Parsers$UnitParser$$anonfun$showSyntaxErrors$2.apply(Parsers.scala:225) [scala-compiler-2.10.2.jar:na]
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772) [scala-library-2.10.2.jar:na]
        at scala.collection.immutable.List.foreach(List.scala:318) [scala-library-2.10.2.jar:na]
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32) [scala-library-2.10.2.jar:na]
        at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45) [scala-library-2.10.2.jar:na]
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771) [scala-library-2.10.2.jar:na]
        at scala.tools.nsc.ast.parser.Parsers$UnitParser.showSyntaxErrors(Parsers.scala:225) [scala-compiler-2.10.2.jar:na]
        at scala.tools.nsc.ast.parser.Parsers$UnitParser.smartParse(Parsers.scala:242) [scala-compiler-2.10.2.jar:na]
        at scala.tools.nsc.ast.parser.SyntaxAnalyzer$ParserPhase.apply(SyntaxAnalyzer.scala:29) [scala-compiler-2.10.2.jar:na]
        at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:464) [scala-compiler-2.10.2.jar:na]
        at scala.tools.nsc.Global$Run$$anonfun$compileLate$2$$anonfun$apply$1.apply(Global.scala:1683) [scala-compiler-2.10.2.jar:na]
        at scala.tools.nsc.Global$Run$$anonfun$compileLate$2$$anonfun$apply$1.apply(Global.scala:1683) [scala-compiler-2.10.2.jar:na]
        at scala.reflect.internal.SymbolTable.atPhase(SymbolTable.scala:207) [scala-reflect-2.10.2.jar:na]
        at scala.tools.nsc.Global$Run$$anonfun$compileLate$2.apply(Global.scala:1683) [scala-compiler-2.10.2.jar:na]
        at scala.tools.nsc.Global$Run$$anonfun$compileLate$2.apply(Global.scala:1682) [scala-compiler-2.10.2.jar:na]
        at scala.collection.Iterator$class.foreach(Iterator.scala:727) [scala-library-2.10.2.jar:na]
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157) [scala-library-2.10.2.jar:na]
        at scala.tools.nsc.Global$Run.compileLate(Global.scala:1682) [scala-compiler-2.10.2.jar:na]
        at scala.tools.nsc.interactive.Global.scala$tools$nsc$interactive$Global$$parseAndEnter(Global.scala:573) [scala-compiler-2.10.2.jar:na]
        at scala.tools.nsc.interactive.Global.backgroundCompile(Global.scala:480) [scala-compiler-2.10.2.jar:na]
        at scala.tools.nsc.interactive.PresentationCompilerThread.run(PresentationCompilerThread.scala:25) [scala-compiler-2.10.2.jar:na]
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/23512053-refactor-import-results-in-corrupted-source-code-if-the-first-line-is-an-import-statement?utm_campaign=plugin&utm_content=tracker%2F239449&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F239449&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Hiroyuki-Nagata**
This is patch for #1029: 
* Rebased #1106

### CODE REVIEW

**Comment by rorygraves** [comment]
@Hiroyuki-Nagata Cool stuff, I will look at this over the weekend, I think it is all good, I just want to run the tests locally (and try and fix drone) but the earliest I'm likely to get to it is tomorrow evening.

**Comment by rorygraves** [comment]
@Hiroyuki-Nagata  II have not fogotten this, I've been failing to get Drone running properly so I was just running them manually.  'm seeing test failures on the 2.10 version

I'm just checking my workings and will post more details howto and error once I've done that.

**Comment by rorygraves** [comment]
Manually run the tests on 2.10 and 2.11 - happy with the change so merging.  Hopefully drone will pick it up for deployment after recent love, but no promises.

**Comment by rorygraves** [comment]
Thanks for the PR @Hiroyuki-Nagata

**Comment by Hiroyuki-Nagata** [comment]
Thanks a lot ! @rorygraves

**Pull request merged**
