### PR TITLE
tidy the sbt build, move sensible defaulty things into their own file

### PR DESCRIPTION
**Pull request by fommil**

### CODE REVIEW

**Comment by fommil** [comment]
Oh joy

**Comment by fommil** [comment]
bizarre consistent failure

```
Some("docs/scala-library-2.11.7-javadoc.jar/index.html#scala.Some@++[B>:A,That](that:scala.collection.GenTraversableOnce[B])(implicitbf:scala.collection.generic.CanBuildFrom[Repr,B,That]):That") was not equal to Some("docs/scala-library-2.11.7-javadoc.jar/index.html#scala.Some@++[B](that:scala.collection.GenTraversableOnce[B]):Option[B]") (DocResolverSpec.scala:286)
```

**Comment by fommil** [comment]
ok, I think this is the cachedResolution bug (doesn't see shapeless)

**Comment by fommil** [comment]
ok, I think I see the 2.10 problem. Fixing now. Still no idea about the javadoc failures.

**Comment by fommil** [comment]
I wonder if we have a corrupted docker image... I'll check

**Comment by fommil** [comment]
nope, that scaladoc file matches the one I have locally.

**Comment by fommil** [comment]
now it fails because of the guava bump, that I can understand.

**Comment by fommil** [comment]
@aemoncannon this failure is driving me crazy, it's supposed to be a no-op refactoring to the build definition, but it's resulting in this consistent error in the doc resolver test

```
Some("docs/scala-library-2.11.7-javadoc.jar/index.html#scala.Some@++[B>:A,That](that:scala.collection.GenTraversableOnce[B])(implicitbf:scala.collection.generic.CanBuildFrom[Repr,B,That]):That") was not equal to Some("docs/scala-library-2.11.7-javadoc.jar/index.html#scala.Some@++[B](that:scala.collection.GenTraversableOnce[B]):Option[B]") (DocResolverSpec.scala:286)
```

any ideas why that might be happening?

**Comment by fommil** [comment]
also, it passes locally and on the AppVeyor. I'll try nuking the docker ivy cache and re-running

**Comment by aemoncannon** [comment]
@fommil 
This seems to hinge on a @usecase difference. Signatures with implicit CanBuildFrom are often replaced in the docs with dumbed-down signatures without the CanBuildFrom. We handle this insanity by actually loading the html in question and checking if the the @usecase signature is present. See DocUsecaseHandling in core.

Is it possible the doc html is available in one case and not in another... or different?

**Comment by fommil** [comment]
@aemoncannon seems to be an identical javadoc jar in both cases.

**Comment by fommil** [comment]
interestingly, we don't close the `JarFile`, but I don't think that's causing this madness.

**Comment by fommil** [comment]
ok, can confirm that the usecase regex isn't catching. I can reproduce in my local docker, but not my local non-docker. I'll close this until I can work out what the problem is.

**Comment by fommil** [comment]
FYI, the usecase matching is failing with "input length = 1"

**Comment by fommil** [comment]
oh, ffs, this might be the `javaOptions += "-Dfile.encoding=UTF8"` line.

**Comment by fommil** [comment]
yeah, it was dropped and it must not be the default in the drone runs. I'm such a moron. I'll reopen after squashing and fixing.

**Comment by fommil** [comment]
@aemoncannon interestingly, if we upgrade to guava 19, the doc resolver tests fail... its finding the scala names for everything instead of the java names.

**Comment by fommil** [comment]
I'm merging before the CI gods change their mind.

**Comment by aemoncannon** [comment]
Hey good catch :)

**Pull request merged**
