### PR TITLE
Filter out structure items without position

### PR DESCRIPTION
**Pull request by ancane**
Fix [ensime-emacs issue 410](https://github.com/ensime/ensime-emacs/issues/410) by filtering out 2 thing:
1. $anon items
2. Items having empty position

### CODE REVIEW

**Comment by fommil** [comment]
LGTM more when you're happy

**Comment by lukasz-golebiewski** [comment]
LGTM

**Comment by fommil** [comment]
I meant to say MERGE when you're ready, but android had different ideas.

**Comment by fommil** [comment]
@ancane sorry, you didn't have permissions. You can merge now.

**Comment by ancane** [comment]
Thanks!

**Pull request merged**
