### PR TITLE
remove deprecated config parameters

### LINKED ISSUE #1347: transient debugger failure
we've seen this a lot recently

```
[info] - should trigger/continue *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: expected DebugBreakEvent(DebugThreadId(1),main,/tmp/1457800313085-0/testing/debug/src/main/scala/breakpoints/Breakpoints.scala,32), found DebugThreadStartEvent(DebugThreadId(1))
```

e.g. http://fommil.com/ensime/ensime-server/268/2

### PR DESCRIPTION
**Pull request by fommil**
close #1347 

introduces a change that may break https://github.com/ensime/ensime-maven/issues/27 and https://github.com/ensime/ensime-gradle/issues/45

### CODE REVIEW

**Comment by chipsenkbeil** [comment]
So, looks like you got rid of the launching debugger, added your own process spawner, and updated code that previously handled start vs. attach to just use attach. Maybe other things I'm missing as well. I'll have to update some of my code, but shouldn't be too bad.

**Comment by fommil** [comment]
oh of course the ensime-emacs debugging tests fail now.

**Comment by fommil** [comment]
a new windows failure

```
- should list/clear *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: expected DebugVmSuccess(success), found DebugVmError(1,com.sun.jdi.VMDisconnectedException: connection is closed,error)
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:339)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:315)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:718)
[info]   at org.ensime.intg.DebugTestUtils$class.withDebugSession(DebugTest.scala:285)
[info]   at org.ensime.intg.DebugTest.withDebugSession(DebugTest.scala:21)
[info]   at org.ensime.intg.DebugTest$$anonfun$3$$anonfun$apply$mcV$sp$3$$anonfun$apply$22$$anonfun$apply$23.apply(DebugTest.scala:135)
[info]   at org.ensime.intg.DebugTest$$anonfun$3$$anonfun$apply$mcV$sp$3$$anonfun$apply$22$$anonfun$apply$23.apply(DebugTest.scala:129)
[info]   at org.ensime.fixture.IsolatedProjectFixture$class.withProject(ProjectFixture.scala:83)
[info]   at org.ensime.intg.DebugTest.withProject(DebugTest.scala:21)
[info]   at org.ensime.intg.DebugTest$$anonfun$3$$anonfun$apply$mcV$sp$3$$anonfun$apply$22.apply(DebugTest.scala:129)
[info]   at org.ensime.intg.DebugTest$$anonfun$3$$anonfun$apply$mcV$sp$3$$anonfun$apply$22.apply(DebugTest.scala:128)
[info]   at org.ensime.fixture.IsolatedTestKitFixture$class.withTestKit(TestKitFixture.scala:41)
```

**Comment by fommil** [comment]
DAAAAAAAAAAAMN IT!!!!!!!!!!


```
- should list/clear *** FAILED ***
[info]   Vector(DebugThreadDeathEvent(DebugThreadId(1)), DebugThreadStartEvent(DebugThreadId(703)), DebugVMDisconnectEvent) did not contain element DebugBreakEvent(DebugThreadId(1),main,C:\Users\appveyor\AppData\Local\Temp\1\1458924500936-0\testing\debug\src\main\scala\breakpoints\Breakpoints.scala,32) (DebugTest.scala:293)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[info]   at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6254)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6300)
[info]   at org.ensime.intg.DebugTestUtils$class.withDebugSession(DebugTest.scala:293)
[info]   at org.ensime.intg.DebugTest.withDebugSession(DebugTest.scala:22)
[info]   at org.ensime.intg.DebugTest$$anonfun$3$$anonfun$apply$mcV$sp$3$$anonfun$apply$22$$anonfun$apply$23.apply(DebugTest.scala:136)
[info]   at org.ensime.intg.DebugTest$$anonfun$3$$anonfun$apply$mcV$sp$3$$anonfun$apply$22$$anonfun$apply$23.apply(DebugTest.scala:130)
[info]   at org.ensime.fixture.IsolatedProjectFixture$class.withProject(ProjectFixture.scala:83)
```

**Comment by fommil** [comment]
*sigh* now getting the slf4j error on windows...

**Comment by fommil** [comment]
on the plus side, the windows debugging tests passed!

**Comment by chipsenkbeil** [comment]
It's like a comedy show reading the comments for this. :D

**Comment by fommil** [comment]
@raboof in this PR I'm also enabling your implicits wildcard test, which only passes under 2.11. It was previously ignored, but it looks like 2.11.8 did indeed fix it.

**Comment by fommil** [comment]
@chipsenkbeil @rorygraves I think JNDI messages from previous tests are clogging next ones, so I'm having to ignore quite a lot from the asynchelper.

**Comment by rorygraves** [comment]
Thinking about this - we have one DebugManager - I suspect that what we actually need is a seperate instance per debug session for message handling.  I guess this is an issue before the move to scala-debugger and the architecture needs some tweaks.  @chipsenkbeil  I'm happy to muck in here - but I guess we need to coordinate changes (maybe just make and debug them on the scala-debugger branch? @chipsenkbeil)

**Comment by rorygraves** [comment]
@fommil  These changes look good - are you ready for merge?

**Comment by chipsenkbeil** [comment]
@rorygraves, I'm all up for coordinating changes on that branch, but it doesn't compile yet. I'm going to be updating it as I implement needed improvements. I created a new actor, DebugActor, rather than removing bits and bobs of code from DebugManager. All of the events from the JDI would be using the standard scala debugger api pipelines. Sounds like we should coordinate a bit on this if you think there are issues with your current actor setup or something that the JDI might run into.

**Comment by rorygraves** [comment]
I think you are heading the right way - Right now there is no separation between debug sessions - I think havign a DebugActor created per debug session and handling all of that sessions messages.  The debug manager can be reworded to manage the upstream connection. (hope that makes sense).

**Comment by fommil** [comment]
@smootoo this is how we fixed the CI failures if you're interested. Once again, akka proves that it really does just like to "let it fail". At random.

**Pull request merged**
