### PR TITLE
FIXME: eliminate all the Option responses

### LINKED ISSUE #1316: RequestHandler FIXME: Find and eliminate all the Option responses legacy
Eliminate Option responses according to [FIXME](https://github.com/ensime/ensime-server/blob/cbacc3d37577be93e68a70c597442961d0e998c6/server/src/main/scala/org/ensime/server/RequestHandler.scala#L49)

### PR DESCRIPTION
**Pull request by ancane**
Heya! Trying to fix #1316
Request handler isn't listening to Options any more. FalseResponses returned from project actors instead. There is a non-RpcResponse family DocSigPair responses left. Wasn't sure if I should change it or not.

### CODE REVIEW

**Comment by fommil** [comment]
cool! This looks sensible. There might be another handler in the WebSockets side, I seem to recall it being added recently.

Tests failing, can you see the error?

**Comment by ancane** [comment]
Thanks for the hint, I'll check websocket handler. Testing failed because of flickering FileWatcherSpec.

**Comment by ancane** [comment]
Hm, I was wrong, flickering test doesn't fail all the suite. The true error is strange:
cask pkg-file: error: Emacs does not exist at /opt/emacs-24.4/bin/emacs.  Did you install Emacs?
[info] build failed (exit code 1)

**Comment by fommil** [comment]
oh damn, I think I might have removed that from the docker image (thought it was unused). Change it to emacs 24.5 in `.drone.yml`

**Comment by ancane** [comment]
Ya! It worked. I changed emacs to 24.5 in drone.yml and removed Option response handling in webserver.

**Comment by fommil** [comment]
Awesome!

**Pull request merged**
