### PR TITLE
Happy family

### PR DESCRIPTION
**Pull request by fommil**
@hedefalk you might want to check the changes/additions in the `JerkFormatSpec` assertions as this will break JERK.

Should not impact SWANK.

First step towards #1006

### CODE REVIEW

**Comment by fommil** [comment]
Note to self: don't forget to update the docker image base scala version after merging.

**Comment by fommil** [comment]
looks like I've introduced a regression in the emacs tests, its hanging forever in the format source test. I'm investigating.

**Comment by fommil** [comment]
@edani @aemoncannon when I run the emacs tests locally, I'm seeing this kind of transient failure a lot now:

```
ENSIME ready. M-x be_cool
Received test event: :compiler-ready
Received :compiler-ready expecting (:compiler-ready :full-typecheck-finished). Waiting for the rest
Received test event: :full-typecheck-finished
Handling test event: :full-typecheck-finished/(:events (:full-typecheck-finished) :func (lambda (G63988) (ensime-test-run-with-handlers Test file with package name (this broke when -sourcepath param was used). (ensime-test-with-proj (proj src-files) (ensime-typecheck-all)))) :is-last nil)
Checking entire project...
Received test event: :region-sem-highlighted
Got :region-sem-highlighted, expecting (:full-typecheck-finished). Ignoring event.
Received test event: :return-value
Got :return-value, expecting (:full-typecheck-finished). Ignoring event.
```

Note there is a `Received test event: :full-typecheck-finished` up there... could we perhaps still have a timing issue when the server starts up "too quickly"?

**Comment by aemoncannon** [comment]
Appears to be waiting for a full type check event that never arrives?

**Comment by fommil** [comment]
@aemoncannon I think it has arrived already, but is being ignored.

**Comment by rorygraves** [comment]
LGTM

**Comment by fommil** [comment]
@hedefalk note that this will impact your JSON protocol

**Comment by edani** [comment]
@fommil  I'll try to look into the transient test errors. Does this happen on more than one unit test? Also what's your configuration? I'm assuming Linux and a not-too-old CPU?

**Comment by fommil** [comment]
Linux and about 4 cores

**Comment by hedefalk** [comment]
Ooh, this isn't published yet, is it?

I went ahead and published the client change https://github.com/hedefalk/ensime-atom/commit/21bc836be23750da106431f482919bd4e7308c29 to atom repo already…

**Comment by fommil** [comment]
@hedefalk should be, unless the ever reliable shippable has let us down again.

**Comment by hedefalk** [comment]
great!

**Pull request merged**
