### PR TITLE
Add matchers to spray.json.JsParserSpec

### PR DESCRIPTION
**Pull request by zainab-ali**
This is a fix for #1909

### CODE REVIEW

**Comment by zainab-ali** [comment]
I'm unsure why the travis build is erroring - everything exits with a status code of 0

**Comment by rorygraves** [comment]
Hi @zainab-ali - Not sure what is going on with the CI there.  Hopefully @fommil  can take a quick look.  I'm not going to get the chance to look until tomorrow evening.  Hopefully somebody can get to it before then.  Other than a flakey CI the changes look great.

**Comment by zainab-ali** [comment]
No worries! Take your time 😃

**Comment by fommil** [comment]
Sorry, will be a while, I've got an eye infection and can't do anything really.

**Comment by fommil** [comment]
can you please do a `sbt fmt` and push the commit? I'll merge after that, I can confirm this should be green... and our CI is very unreliable.

**Comment by zainab-ali** [comment]
done.  I'll be sure to do that before pushing in future.

**Comment by fommil** [comment]
the sbt-scalafmt plugin could do with an upgrade.

**Pull request merged**
