### PR TITLE
Add EnsimeProject to EnsimeConfig

### PR DESCRIPTION
**Pull request by yyadavalli**
Simple addition of EnsimeProject

### CODE REVIEW

**Comment by fommil** [comment]
cool! But we don't need to support the old format at all, so you can remove stuff :grinning:

**Comment by yyadavalli** [comment]
From sbt-ensime too ??  I forgot if the clients used the .ensime for anything.

**Comment by fommil** [comment]
no, `sbt-ensime` needs to be backwards compatible. But the server only needs to read the new bits.

**Comment by yyadavalli** [comment]
I keep forgetting we use the same plugin for 1.0, also i'd prefer to merge it this way. We can remove once the changes are integrated downstream in the analyzer and file watchers, or else we have to reconstruct `compileClasspath` and others in `EnsimeConfig`.

**Comment by fommil** [comment]
ok, fair enough. I want to do some changes on the sbt plugin first, some naming etc. Sorry I've been slow on it, but I'll definitely get to it by the next hack day (5th december). I'm currently moving the plugin over to use coursier.

**Comment by yyadavalli** [comment]
That's fine, even I didn't get a chance to finish the deduping in the plugin. Just thought of adding this in as I already had it done locally. The coursier move should be good.

**Comment by fommil** [comment]
needs an update for the new format

**Comment by fommil** [comment]
closing until updated for the new api (no need to create a new PR... just push here if you get round to this and we'll reopen)

**Comment by yyadavalli** [comment]
I will work on this next week after my exams

**Pull request closed without merging**
