### PR TITLE
bump sbt-ensime

### PR DESCRIPTION
**Pull request by fommil**

### CODE REVIEW

**Comment by rorygraves** [comment]
LGTM

**Comment by rorygraves** [comment]
lgtm

**Comment by rorygraves** [comment]
LGTM

**Comment by fommil** [comment]
LGTM

**Comment by fommil** [comment]
requires two approvals, but we can customise https://lgtm.co/docs/customize/

I think it is actually good to need two, even if its my own PR because it's like a signal that "I'm ready for this to be merged". Often I have WIP branches.

**Pull request merged**
