### PR TITLE
Scala 2.9

### PR DESCRIPTION
**Pull request by fommil**
always painful...

### CODE REVIEW

**Comment by fommil** [comment]
ok, **this** time the jenkins build isn't set up to handle the specificities of 2.9 :smile:

**Comment by fommil** [comment]
I found an sbt problem... we're not building the 2.9.2 branch properly thanks to the sbt caching magic. I'll add a patch in a moment.

**Comment by fommil** [comment]
yay

**Comment by fommil** [comment]
@rorygraves maybe we should turn off Jenkins now that Travis seems to be working again?

**Comment by rorygraves** [comment]
I think we should leave it on for now - there is a bunch of other stuff I would like to do which would require dependent builds and cleverness that even the new funky travis doesn't support.

**Comment by rorygraves** [comment]
but still, pretty cool that using docker travis is now reliable.

**Comment by fommil** [comment]
ok, thanks for that coveralls.

**Pull request merged**
