### PR TITLE
Crossbuild

### PR DESCRIPTION
**Pull request by fommil**
not wired up to drone yet because we need drone 0.4 for matrix build support (released upstream in a week or so). The tests pass for me locally, not tried the emacs tests yet.

### CODE REVIEW

**Comment by fommil** [comment]
@koshelev might like this

**Comment by fommil** [comment]
grr, 2.11 build fails now as we're using a deprecated method. Easy fix, I'll do that tomorrow.

**Comment by fommil** [comment]
the appveyor failure looks like a transient due to lack of their CPU resources

**Comment by fommil** [comment]
we seem to get this transient a lot on windows

```
[info] - should trigger/continue *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: expected TrueResponse, found FalseResponse
...
[info]   at org.ensime.intg.DebugTest$$anonfun$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$6$$anonfun$apply$19$$anonfun$apply$20.apply(DebugTest.scala:59)
```

**Comment by rorygraves** [comment]
@fommil  build is failing with formatting error

**Comment by rorygraves** [comment]
Nice, 2.10 is back!

**Pull request merged**
