### PR TITLE
Stage 0: Analyzer per Project

### PR DESCRIPTION
**Pull request by fommil**
most of #1790

### CODE REVIEW

**Comment by fommil** [comment]
@VC1995 following this, the Stage 1 should rethink how reloading of scala compilers is handled... perhaps we should add support to an `Analyzer` to go "dormant" for a while (i.e. persist its list of open files and allow the `scalaCompiler` to be garbage collected)

**Comment by fommil** [comment]
what the hell? On Windows we're getting a compiler warning compling from `Predef` 

```
NewScalaNotesEvent(false,List(Note(C:\Users\appveyor\.coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-library\2.12.2\scala-library-2.12.2-sources.jar!/scala/Predef.scala,Procedure syntax is deprecated. Convert procedure `assume` to method by adding `: Unit =`.,NoteWarn,11861,11861,233,35)))
```

in `BasicWorkflow` instead of the final `FullTypeCheckCompleteEvent`.

**Comment by fommil** [comment]
@sugakandrey do you think it might be possible that reverse lookup is loading Predef on Windows but not on any other platform?

**Comment by sugakandrey** [comment]
@fommil no idea honestly, I don't have a windows machine, so I've never really gotten to testing windows shenanigans properly

**Pull request merged**
