### PR TITLE
Deprecation extends to member of classes/traits/objects #1023

### PR DESCRIPTION
**Pull request by ale64bit**
@fommil Sorry, I was testing some corner cases and forgot to PR.

### CODE REVIEW

**Comment by fommil** [comment]
You might need to issue a corresponding PR for the Emacs tests, as this likely breaks the assertion.

**Comment by ale64bit** [comment]
mmm, that's right.

**Comment by ale64bit** [comment]
Actually, I think it doesn't break the assertion. Why the build is failing?

**Comment by fommil** [comment]
looks like it was just shippable being crap. I really need to move us over to `drone.io`.

**Comment by fommil** [comment]
shippable has decided it doesn't want to rerun the build. Can you please rebase to master to force it to do so?

**Comment by ale64bit** [comment]
> Can you please rebase to master to force it to do so?

Sorry, how do I do that exactly?

**Pull request merged**
