### PR TITLE
Add `typeParams` to `ArrowTypeInfo`. Closes #1504

### LINKED ISSUE #1504: ArrowTypeInfo should have a list of type parameters
Currently it's not possible to regenerate the list of type params for a generic method based on `typeInfo` content.

### PR DESCRIPTION
**Pull request by ktonga**
Still want my stickers @fommil

### CODE REVIEW

**Comment by ktonga** [comment]
Emacs tests failed, I guess it has something to do with a test asserting the exact response from the server. If this is the case, it's ok that it fails since a new field has been introduced, and as far as I could see, empty lists are included in the serialised body. Excluding `None`s and empty `List`s from the serialisation (or the assertion) could be a way for the tests to need less attention I think.

**Comment by fommil** [comment]
Which country are you in?

**Comment by fommil** [comment]
Hmm, might be cheaper to get a fresh batch made up.

**Comment by ktonga** [comment]
I'm in Australia/Sydney. Just joking, did't want to bother you, I read it in the PR template.

**Comment by fommil** [comment]
@ktonga no no, we need to get some stickers out there, but you'll be responsible for mailing them to other AU/NZ contributors  :stuck_out_tongue:

**Comment by fommil** [comment]
ok, definitely something funky going on with the drone build. This is more or less the same thing we see in the graphpocalypse @sugakandrey I'm all out of ideas, this has come from nowhere.

**Comment by fommil** [comment]
maybe the answer is to just not bail if we fail to delete that directory, and just log it instead.

**Comment by fommil** [comment]
LGTM the honour is all yours to merge!

**Comment by fommil** [comment]
:tada:

**Pull request merged**
