### PR TITLE
Lookup definition jumps to function definition

### PR DESCRIPTION
**Pull request by VlachJosef**
Make Lookup definition jump to definition of a function
instead of apply method in FunctionX trait

### CODE REVIEW

**Comment by fommil** [comment]
oh awesome! I've been waiting for this one :smile: a bit too late right now but I'll definitely have a good review of this at the weekend.

This technically breaks the API (because we're not actually returning information about the thing at point) but I consider `FunctionX` to be a language implementation detail and therefore we should never be seeing it.

**Comment by fommil** [comment]
actually it was so short it is easy to see what it's doing. Great stuff! Is it possible to write a standard RichPresentationCompilerSpec for this?

**Comment by VlachJosef** [comment]
You right about breaking API, both eclipse and intellij idea give you an option where you wants to jump, but frankly I never wants to jump to `FunctionX.apply` method. A consider this breaking API change as a big productivity booster as it streamline workflow. In the case someone wants to jump into `FunctionX.apply` method, the easy way is just to add `.apply` to a function definition, so in a sense there is no functionality hidden from users. This behaviour should probably be described in a documentation. Where it would be best to put it?

**Comment by VlachJosef** [comment]
I'll try to write spec in RichPresentationCompilerSpec over the weekend.

**Comment by fommil** [comment]
if the user really wants to look at `Function2.apply` they can find it with `ensime-search`. Does this close any tickets?

**Comment by VlachJosef** [comment]
No, I doesn't close any ticket.

**Comment by fommil** [comment]
hmm, interesting... looks like you're getting failed tests on Linux, but not Windows. I wonder if the test is sensitive to the version of Java?

```
[info]   java.lang.AssertionError: assertion failed: expected:  but got unexpected message Some(SymbolInfo(apply,apply,Some(OffsetSourcePosition(/tmp/1450396448450-0/.ensime_cache/dep-src/source-jars/scala/Function1.scala,1665)),ArrowTypeInfo((v1: T1)R,136,BasicTypeInfo(R,137,Nil,scala.R,List(),List(),None,None),List(ParamSectionInfo(List((v1,BasicTypeInfo(T1,135,Nil,scala.T1,List(),List(),None,None))),false))),true,Some(138)))
[info]   at scala.Predef$.assert(Predef.scala:165)
[info]   at akka.testkit.TestKitBase$class.expectMsgPF(TestKit.scala:357)
[info]   at akka.testkit.TestKit.expectMsgPF(TestKit.scala:718)
[info]   at org.ensime.intg.BasicWorkflow$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$10$$anonfun$apply$11.apply(BasicWorkflow.scala:188)
```

**Comment by VlachJosef** [comment]
Hm, I will change the tests. It looks like it is failing when checking offset in the `Function1.scala` file. Since this is external source checking offset is not good idea anyway.

**Comment by VlachJosef** [comment]
Ok, I've added RichPresentationCompilerSpec spec and remove checking of offset in `Function1.scala` file. Tests should now pass.

**Comment by fommil** [comment]
Great stuff! This will really improve things for functional libraries

**Pull request merged**
