### PR TITLE
Cleanup deprecated API usage in build

### PR DESCRIPTION
**Pull request by yyadavalli**
Simple cleanup of old API usages

### CODE REVIEW

**Comment by fommil** [comment]
`org.ensime.core.DocResolverSpec` failing. I can't see why that would happen

**Comment by yyadavalli** [comment]
Me too, didn't get a chance to look at it till now. Also, it is happening only on the drone build

**Comment by fommil** [comment]
I restarted, but I'm totally confused about what's going on.

**Comment by fommil** [comment]
it might be that the docker image was rebuilt with some unexpected changes

**Comment by yyadavalli** [comment]
Looks like its still failing...

**Comment by fommil** [comment]
I'll investigate, might be the weekend before I get to it.

**Comment by yyadavalli** [comment]
Sure, let me know if can help with anything

**Comment by fommil** [comment]
I'll pull this in with one of my PRs, the warnings are also annoying **me** :smile:

**Pull request closed without merging**
