### PR TITLE
Banish type-ids to the land of wind and ghosts

### PR DESCRIPTION
**Pull request by aemoncannon**
The emacs client only uses CallCompletionInfo at this point, and I believe I can get rid of that by making small tweaks to CompletionSignature, which is returned with the CompletionInfo objects. In the mean time, let's get all the client teams on the same page (my guess is not many folks use this stuff..).
@rorygraves @fommil

### CODE REVIEW

**Comment by fommil** [comment]
Great! This is something we've wanted to do for a while

**Comment by aemoncannon** [comment]
@rorygraves @yazgoo @hedefalk
Just a heads up. In the next few days I hope to have a PR to remove these deprecated items from the protocol. Please reply here if you have any concerns.

**Comment by fommil** [comment]
I am extremely concerned by Donald Trump.

**Comment by aemoncannon** [comment]
Don't worry. I'm pretty sure he is just a conceptual art project.

**Comment by fommil** [comment]
curse your infernal documentation formatting!

**Comment by fommil** [comment]
@aemoncannon btw, incase you didn't catch it... this failed because of bad formatting in `b/api/src/main/scala/org/ensime/api/incoming.scala`

**Comment by rorygraves** [comment]
@aemoncannon Sublime does not use any of the deprecated calls, but one of the deprecated types -TypeInfo (specifically ArrowTypeInfo) uses ParamSectionInfo, so that can't go get.

**Comment by rorygraves** [comment]
Whoops, sorry, meant Comment not 'Close and Comment'

**Comment by aemoncannon** [comment]
@rorygraves Thanks! That's exactly the kind of feedback I was hoping for.

**Comment by aemoncannon** [comment]
*phew* Updated this PR to actually remove all type-ids. Please don't merge until I at least fix emacs client to work with this!

**Comment by aemoncannon** [comment]
@rorygraves @yazgoo @hedefalk
See CHANGELOG edits for client team action items.

**Comment by fommil** [comment]
Great stuff! Been wanting to do this for a long time but it was always bottom of the list. The protocol should be a lot easier to understand now

**Comment by aemoncannon** [comment]
Yep!

Btw, emacs integration failure is expected. I'll re-kick the CI once the lisp is updated.

**Comment by hedefalk** [comment]
ensime-atom should be safe. We're not using CallCompletionInfoReq,TypeByIdReq, InspectTypeByIdReq or any typeId's.

**Comment by aemoncannon** [comment]
The server code is green on CI, just the out-of-date elisp that's failing. I'm going to go ahead and merge this as I have time right now to do the necessary cleanup.

**Pull request merged**
