### PR TITLE
Add support for repeated params in TypeToScalaName

### PR DESCRIPTION
**Pull request by iravid**
This solves #1499.

Not sure if 2.0 is the right base branch, but it was the default for the repo so I ran with it. Let me know this needs to be rebased on 1.0.

### CODE REVIEW

**Comment by fommil** [comment]
Impressive :-)

**Comment by aemoncannon** [comment]
Great PR!

**Comment by iravid** [comment]
Thanks! I'll try to find time for the by-name issue over the weekend.

**Comment by fommil** [comment]
LGTM

**Comment by fommil** [comment]
If you want to use the 2.0 from your editor you'll need to manually set it up. It's kind of developers only right now because we might break the api for short periods of time

**Comment by iravid** [comment]
Thanks. I'll stick with 1.0 for my editor :-)

**Comment by fommil** [comment]
You could raise this against 1.0 if you really want it, I can't see this code breaking anything

**Comment by aemoncannon** [comment]
Yes, please!

**Comment by iravid** [comment]
Sure thing, will do.

**Pull request merged**
