### PR TITLE
Export jars

### LINKED ISSUE #1234: bundle the JDK 6 tools sources
All the OpenJDK sources are tagged here

  http://hg.openjdk.java.net/jdk8u/jdk8u/tags

instead of requiring the user to bundle this, we should just ship a zip of the official JDK of our build, and then merge this back into `ensime-sbt` to simplify the testing (which also requires this manual step).

### PR DESCRIPTION
**Pull request by fommil**
I've rewritten the file watchers to be more efficient, fixed some epic bugs in the indexer (if it ever worked for watched files, it did it by accident) and added support for `.jar` targets via `useJar` https://github.com/ensime/ensime-sbt/blob/v0.3.3/src/main/scala/EnsimePlugin.scala#L43-L46

closes #1234 #1230 #1042 and some housekeeping.

### CODE REVIEW

**Comment by fommil** [comment]
Notes to self:

- take one dir per constructor, not a Set
- make the jar watcher take a different selector and be non-recursive with its own tests.

**Comment by greenrd** [comment]
What does this do? Needs a doc PR as well.

**Comment by fommil** [comment]
@greenrd it's very alpha, just for comment.

**Comment by fommil** [comment]
I'm getting somewhere with this! The JDK6 filewatchers are a lot better already, and the JDK7 ones thanks to @lxol will be far better. I'll try to pull that over the line this weekend.

**Pull request merged**
