### PR TITLE
A couple java things that were broken in the shuffle.

### PR DESCRIPTION
**Pull request by aemoncannon**

### CODE REVIEW

**Comment by fommil** [comment]
I'm actually putting together a tiny PR around the ensime-sbt langtools source files. I'll fix the obvious `EnsimeConfig` / classpath bug while I'm there. I'm not sure what to do about the messages on startup though. Maybe worth just fixing it in the client?

**Comment by aemoncannon** [comment]
Re messages. I'd rather not change the clients. Can we just keep the
behavior consistent with Scala for now?

**Comment by fommil** [comment]
No problem... we can always change the client later when the java stuff gets its own message set (or just drop it if we have time and it makes sense). I'm going to bed now but I think you're going to need to change the assertion in `ProjectFixture` for the integration tests to pass. Can you please merge my PR if it goes green? That'll at least fix the classpath issue.

BTW, if you download the drone client (and have docker installed) you can run the full CI tests locally by typing `drone exec` http://readme.drone.io/docs/cli/index.html

**Comment by aemoncannon** [comment]
I'll rebase to yours once it goes green and you merge.

**Comment by aemoncannon** [comment]
@fommil Appveyor failing in some kind of websocket flow test. My guess is it's a flaky test. Would you take a look?

**Comment by fommil** [comment]
Hmm, I don't see why that test should fail. Might just be dodgy running out cheap hardware, an it often does at that time of night.

**Comment by fommil** [comment]
Actually I believe the integration tests should fail with this update. You'll need to update the expectations of the project fixture as its going to be seeing a lot more messages on startup now.

**Comment by aemoncannon** [comment]
Oh, duh. We'll be sending them once for Scala and once for Java. Hmmm. I think you were right in the first place and I should just fix the elisp to no longer wait for analyzer-ready.

Will this break anything server side? does server queue things correctly if client starts sending stuff before the pres compiler is ready?

**Comment by aemoncannon** [comment]
On third thought, that'd be a pretty disruptive change. Also, from a UI standpoint, it's nice to know when things are ready. Either we do it explicitly with analyzer-ready, or we do it implicitly by making the user wait for the rpc queue to drain -- I like the former.

**Comment by aemoncannon** [comment]
Here's an idea: we wait at Project for CompilerReady from *both* Analyzers, then we send the single CompilerReady to the client. This comes with no external behavior change, as java ready will be instantaneous.

**Comment by rorygraves** [comment]
That would work (waiting for both internally and emitting only one)

**Comment by fommil** [comment]
The server does the right thing. From an API perspective, as soon as you get the connection info message, you're good to go.

**Comment by fommil** [comment]
Re: sending only once. Have a look at broadcaster. We could make it not send duplicate persisted messages and I think that achieves what you want.

**Comment by fommil** [comment]
I'll be home in about an hour, I can put together a small PR unless you get there first. Broadcaster feels like the right place and might just be a change of a List to a Set.

**Comment by fommil** [comment]
It'd be really nice if the UI didn't care though :-)

**Comment by fommil** [comment]
ha! `Broadcaster` already does what I was suggesting. That means the client should only see these messages once.

**Comment by fommil** [comment]
see #1129

**Pull request closed without merging**
