### PR TITLE
Merge SWANKY stuff into 2.0-graph

### PR DESCRIPTION
**Pull request by sugakandrey**

### CODE REVIEW

**Comment by fommil** [comment]
LGTM

**Comment by fommil** [comment]
I don't know, this looks like a real regression, all OS are failing. Bad merge?

I restarted the emacs tests against master to prove that they work http://fommil.com/ensime/ensime-emacs/378

**Comment by fommil** [comment]
(it is possible that Windows and OS X were transient... it happens)

**Comment by sugakandrey** [comment]
appveyor & travis failures definitely look transient, I doubt I messed them up for real.

**Comment by fommil** [comment]
travis looks like it created a bad cache, so I cleared it and restarted. The Emacs error looks real though.

**Comment by fommil** [comment]
LGTM

**Pull request merged**
