### PR TITLE
SWANK refactor progress toward #390

### PR DESCRIPTION
**Pull request by fommil**
This PR might seem a bit weird, but it's working towards a noble goal.

It shouldn't change the protocol in any way, but to simplify things I removed some of the deprecated endpoints.

The current protocol handling code is layered something like this:

1. raw socket => String
2. String => SExp (old implementation)
3. Sexp => raw parameters
4. raw parameters => synchronous methods
5. ... S-Exp primadonna actors ENSIME ...
6. domain model => S-Express
7. Sexp => String
8. String => socket

but we'd like to get to

1. socket => WireFormat (JSON / XML / S-Exp)
2. WireFormat => domain model
3. ... protocol independent reactive ENSIME ...
4. domain model => Sexp
5. Sexp => socket

and unfortunately this PR seems to muddy the water by bringing us to

1. raw socket => Sexp
2. Sexp => domain model
3. model => synchronous methods
4. ... S-Exp primadonna actors ENSIME ...
5. domain model => Sexp
6. Sexp => socket

but at least we're converging on the desired architecture :-)

Lots of String => File and CanonFile => File as a result of canonisation now occurring at the protocol level. Ideally .canon would only be used when information is entering the system. I might have broken things for OS X.

Also, the `SwankProtocolConversions.scala` file is really becoming a monstrosity (sorry!). It exists entirely to implement the current SWANK protocol and this simplify reflects that we marshall every object in a slightly different way. Hopefully, once we get 1.0 out the door, we can look at using the "natural S-Exp form" which will involve a lot of changes on the Emacs side (nothing functional, just data structures), and this file will vanish thanks to shapeless.

### CODE REVIEW

**Comment by rorygraves** [comment]
Awesome stuff.

**Comment by rorygraves** [comment]
Seems to work find on Mac - @aemoncannon  @edani  Any comments before I merge this?

**Comment by fommil** [comment]
don't forget to read `SwankProtocolConversions.scala` via a mirror http://en.wikipedia.org/wiki/Medusa

**Comment by rorygraves** [comment]
It also makes me sad the Ensime dislikes one of its own files - too many implicits....

**Comment by fommil** [comment]
dag namnit

**Comment by fommil** [comment]
crap, that was an accidental push. I'll revert.

**Comment by rorygraves** [comment]
Ok, pulling the trigger

**Pull request merged**
