### PR TITLE
[Sponsored] Analyzer per Project

### PR DESCRIPTION
**Pull request by VC1995**
Extended `BasicWorkflow` to show that symbol tables are not shared between presentation compilers.

### CODE REVIEW

**Comment by VC1995** [comment]
I wonder why I sometimes fail "should shutdown if preferred TCP port is not available" on Windows.
Also the added tests work as long as the sbt-ensime fix doesn't come in. Then the test configuration will automatically load the symbols of "compile" configuration we will no longer get the scala notes saying "not found: value Bloo"

**Comment by fommil** [comment]
@VC1995 please upgrade `sbt-ensime` and we'll see how it does

**Comment by fommil** [comment]
of course, I can do it too :smile: let's see how that does

**Comment by VC1995** [comment]
@fommil As expected : `expected class org.ensime.api.NewScalaNotesEvent, found class org.ensime.api.FullTypeCheckCompleteEvent`

**Comment by VC1995** [comment]
I am guessing now the "test" configuration is depending on "compile". So we find the Blue class definition in the "compile" configuration and don't get the `NewScalaNotesEvent` as we earlier expected.
Should I modify the BasicWorkflow according to what we expect now ? :-)

**Pull request merged**
