### PR TITLE
disable coverage in the testing modules

### PR DESCRIPTION
**Pull request by fommil**

### CODE REVIEW

**Comment by aemoncannon** [comment]
lgtm

**Comment by fommil** [comment]
important thing is if this fixes the coverage problem on travis...

**Comment by rorygraves** [comment]
We wait with eager anticipation.

**Comment by fommil** [comment]
oh damn, I thought I could pinch all @rorygraves's work while he was off sick and pass it off as my own... but now I've been caught out

**Comment by rorygraves** [comment]
lol, I wish that were true - this is all you.

**Comment by fommil** [comment]
perfectly timed with the failure

**Comment by fommil** [comment]
W00000TT!!! Screw you, coverage jerk! :stuck_out_tongue:

**Comment by fommil** [comment]
@rorygraves did you fix the coveralls plugin? Because now coveralls can link to the files again. Maybe they fixed it on the server side and didn't require a full path...

**Comment by rorygraves** [comment]
not yet - been offside for the past 4 days and haven't looked at anything.

**Comment by aemoncannon** [comment]
Yeah!

**Pull request merged**
