### PR TITLE
single jar deploys

### PR DESCRIPTION
**Pull request by fommil**
sbt-scoverage now works, ~~but I've not enabled it because the debug tests fail when run with coverage (getting debug exceptions instead of values, things like that... probably interacting in a strange way with the profiled code)~~ but I've not made it fail the build if coverage is too low. We need #1091 for that.

### CODE REVIEW

**Comment by fommil** [comment]
@sksamuel any ideas why we might be seeing exceptions when debugging code that has been profiled with scoverage? Do the instrumented classes throw any exceptions for tracing purposes?

**Comment by fommil** [comment]
actually, I just remembered how to turn off the instrumentation of our test packages. I'll do that, it should fix it.

**Comment by sksamuel** [comment]
They only write out to disk, so maybe there's an issue with that and you're
seeing an IOException ?

**Comment by fommil** [comment]
@sksamuel I remembered that we needed to disable instrumentation of the code that we were running under debug mode.

**Comment by fommil** [comment]
Great, a typo in the drone file

**Comment by fommil** [comment]
sorry, CI is so slow... we're waiting on drone adding back in the multiple build hosts support. It's currently only using one node on one box (we have at least 3 idle)

**Comment by fommil** [comment]
Damn you drone

**Comment by fommil** [comment]
thank the maker!

**Pull request merged**
