### PR TITLE
Migrate tests to EnsimeSpec

### PR DESCRIPTION
**Pull request by ancane**
Issue #1245
Migrated all tests to become EnsimeSpec and changed asserts to should machers where it was possible. Didn't play with EnsimeVFS yet. I'd prefer to move tests from Int into test with another pr, as this one is already huge. Same for deprecated AkkaFlatSpec. Thanks.

### CODE REVIEW

**Comment by fommil** [comment]
great! This must have taken a long time, it is appreciated.

I want to go through and check everything because it'd be a real pain if a silly regression managed to slip in, so I'll do that before merging.

One comment: I noticed you use `should ===` but I think this can be replaced with `shouldBe` (equality) or `shouldEqual` (uses scalactic equality)

**Comment by ancane** [comment]
In general, I was replasing `==` by `shoulBe` and `===` by `should ===` to preserve compile-time type constraint. Shoul I replace all equality checks with shoudBe?

**Comment by fommil** [comment]
ok, I didn't realise `===` did type checking, we can keep that. The only outstanding comment from me is the `Try` vs `intercept`

**Comment by ancane** [comment]
And I didn't realize I should mixin `TypeCheckedTripleEquals` to have that compile time check working. By defaul `===` is still a runtime check.

**Comment by ancane** [comment]
DescriptorParserSpec now intercepts parser exceptions.

**Comment by fommil** [comment]
great stuff! :-)

**Pull request merged**
