### PR TITLE
Go to declaration for Java (WIP)

### PR DESCRIPTION
**Pull request by aemoncannon**
TODO:
 * Implementation of askLinkPos to get fine-grained positions.
    ** should be pretty easy. just need to parse the file, then walk the tree looking for the element

### CODE REVIEW

**Comment by aemoncannon** [comment]
Btw, I love having the elisp tests running for the server. Such warm feels.

**Comment by fommil** [comment]
heh, I think I'd go with "less nervous"

**Comment by fommil** [comment]
interestingly it fails on windows too.

Btw, you can force a JDK in `sbt` if you're using paulp's `sbt-extras` by creating a `.sbtopts` file.

**Comment by aemoncannon** [comment]
Oh good tip

**Comment by aemoncannon** [comment]
@fommil Been hitting some sexp <=> string QuickCheck failures. Can you make any sense of it?

**Comment by fommil** [comment]
If they happen just restart. They are extremely rare.

**Comment by aemoncannon** [comment]
Woo! I had relax the test to make this pass, but I think I know how to fix things. The root of the trouble is in looking up Elements given a Tree or a Type. I've got some ideas how to make this more robust across JVMs.

**Comment by fommil** [comment]
Prepare thyself for the hack day tomorrow :-|

**Comment by aemoncannon** [comment]
Should I be worried? : )

**Comment by fommil** [comment]
Apparently there might be 10+ people there keen to do ENSIME stuff. Although might be mostly sublime, Vim and atom.

**Comment by aemoncannon** [comment]
Hey that's pretty awesome. At some point I want to evangelize at work and
the additional clients will be a great selling point :)

**Comment by fommil** [comment]
I think Josh of SBT fame recently rejoined you. Maybe hunt him down?

**Pull request merged**
