### PR TITLE
Move to akka.io and improve error handling

### PR DESCRIPTION
**Pull request by rorygraves**
Fundamentally there are two changes here:

1. Move from raw sockets to akka.io for socket protocol handling.
2. Create a top level actor that is responsible for handling core actor failures and shutdown gracefully.

### CODE REVIEW

**Comment by fommil** [comment]
this is looking good, I've been using it all day, but we need the fix for the missing file as that will impact a lot of people since we are more likely to see the server bail on errors because we're not restarting the analyser on exceptions, so that's something we should keep in mind over the coming weeks.

**Comment by rorygraves** [comment]
@fommil  @greenrd  I've pushed an extra change to this PR to address #930 - the call should now return an error rather than causing the Analyser to fail.    I have not had time to test it in anger - I plan to add a test, but realistically that will not occur until tomorrow evening.  Feel free to have a play.

**Comment by rorygraves** [comment]
@fommil  Added a test as well, missing file on typecheck reports an error rather than failing server - back to you.

**Comment by rorygraves** [comment]
@rorygraves   - Aide memoir
```
Received test event: :indexer-ready
Received :indexer-ready/t expecting (:connected :compiler-ready :indexer-ready :full-typecheck-finished) with guard func nil. Waiting for the rest
06:29:48.068 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1 a.a.LocalActorRef - unhandled message from Actor[akka://ENSIME/user/ensime-main/project#1319839364]: RpcResponseEnvelope(Some(1),ConnectionInfo(None,EnsimeImplementation(ENSIME),0.8.17))
```

**Pull request merged**
