### PR TITLE
Fix for #1267

### PR DESCRIPTION
**Pull request by msiegenthaler**
Fixes the ClassCastException when executing DocUriAtPointReq over HTTP-RPC (no websocket).
Needed to add the same multi phase logic as in RequestHandler.

### CODE REVIEW

**Comment by msiegenthaler** [comment]
Sorry for not adding a testcase, but there was no infrastructure in place for this sort of test.

**Comment by msiegenthaler** [comment]
#1272 is closely related, adding a fix for that as well.

**Comment by fommil** [comment]
Can you please squash? We'll accept this for now but I suspect this will be removed. Should be trivial to add a test, no? Isn't there a test framework for akka-http?

**Comment by msiegenthaler** [comment]
Squashed it.

Does it help if I do another pull request removing the whole HTTP-RPC stuff to be merged later on?

**Comment by fommil** [comment]
yeah, please do... send it to us when you are transitioned to WebSockets.

**Pull request merged**
