### PR TITLE
appveyor windows build

### PR DESCRIPTION
**Pull request by fommil**
for reviewing the "PR Of Doom", I thought maybe @edani deserved some Windows safety :-P

### CODE REVIEW

**Comment by fommil** [comment]
wow, this is actually working! I think it will also be feasible to add the emacs tests like we do in the Linux build. No need to publish/coverage/check syntax.

**Comment by fommil** [comment]
I think they definitely deserve having their logo added to the ENSIME talk for ScalaDays next week.

**Comment by fommil** [comment]
```
java.io.FileNotFoundException: Could not automatically find the JDK/lib/tools.jar.
You must explicitly set JDK_HOME or JAVA_HOME.
	at JdkResolver$$anonfun$8.apply(EnsimeBuild.scala:260)
	at JdkResolver$$anonfun$8.apply(EnsimeBuild.scala:260)
```

OK, but I'm sure this can be fixed by prepping the JDK environment.

**Comment by edani** [comment]
@fommil   Cool!  The current master does have a few Windows failures (I'll have a PR out very soon)  , let's see if it catches them!

**Comment by fommil** [comment]
Any ideas why the tools jar detection fails?

**Comment by fommil** [comment]
Oh my god shippable, you are a disaster!

**Comment by edani** [comment]
I don't know why tools.jar isn't found, maybe that instance has the JRE and not the JDK installed?

**Comment by fommil** [comment]
That is hard to believe, it means javac would be absent.

**Comment by fommil** [comment]
anyway, I'll have to park this for a week as I have a lot of travel coming up.

**Comment by fommil** [comment]
btw, the Drone build here is a server running on my machine... not `drone.io`

Has a couple of niggles, but when it starts to work we can kill Shippable.

**Comment by fommil** [comment]
Drone fails emacs tests with
```
emacs: standard input is not a tty
```

so probably some envvar thing.

**Comment by fommil** [comment]
interesting, the windows tests are failing with

```
[info] Exception encountered when attempting to run a suite with class name: org.ensime.jerk.JerkFormatsSpec *** ABORTED ***
[info]   java.lang.StackOverflowError:
[info]   at org.ensime.jerk.JerkConversions$$anonfun$1$fresh$macro$1762$1.inst$macro$1396(JerkFormats.scala:38)
[info]   at org.ensime.jerk.JerkConversions$$anonfun$1$fresh$macro$1762$1.inst$macro$1396$lzycompute(JerkFormats.scala:38)
[info]   at org.ensime.jerk.JerkConversions$$anonfun$1$fresh$macro$1762$1.inst$macro$1396(JerkFormats.scala:38)
```

which I've seen before due to dodgy ivy caching. Surely windows stack sizes are the same as linux.

**Comment by fommil** [comment]
unit tests are passing in windows, but integration tests fail with

```
- should open the test project *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: expected:  but got unexpected message SymbolSearchResults(List(TypeSearchResult(java.util.Random,Random,Class,Some(LineSourcePosition(C:\Users\appveyor\AppData\Local\Temp\1\ensime-it-BasicWorkflow-903314846821865250.project\.ensime_cache\dep-src\source-jars\java\util\Random.java,91))), TypeSearchResult(scala.util.Random,Random,Class,Some(LineSourcePosition(C:\Users\appveyor\AppData\Local\Temp\1\ensime-it-BasicWorkflow-903314846821865250.project\.ensime_cache\dep-src\source-jars\scala\util\Random.scala,21)))))
[info]   at scala.Predef$.assert(Predef.scala:165)
[info]   at akka.testkit.TestKitBase$class.expectMsgPF(TestKit.scala:357)
```

so I'm going to disable the integration tests to get us started. It's something!

**Comment by fommil** [comment]
wow, that's actually the only failure on windows.

**Comment by fommil** [comment]
Also, worth noting that the slow-as-shit windows boxes from AppVeyor manage to finish **before** shippable.

**Comment by FeodorFitsner** [comment]
Your account is actually on a new environment with the latest CPUs and SSD. Slow-as-shit was before that ;)

**Comment by fommil** [comment]
@FeodorFitsner ha! Well it has just gotten a lot faster in the last two builds. This:

```
'compiler-interface' not yet compiled for Scala 2.11.7. Compiling...
[info]   Compilation completed in 30.075 s
```

used to be more like 600s. Thanks for the bump! (intentional or not :stuck_out_tongue: )

**Comment by FeodorFitsner** [comment]
It's intentional of course :) We are moving all accounts to the environment.

**Comment by fommil** [comment]
well it's a great move. Thanks for this service!

**Comment by fommil** [comment]
@FeodorFitsner any chance of having `sbt` (i.e. most scala projects) and `emacs` installed by default? It would save a lot of faffing around with manual scripting.

**Comment by FeodorFitsner** [comment]
Where can I read about `sbt`? Sorry, I'm mostly a Windows guy :)

**Comment by fommil** [comment]
@FeodorFitsner checkout out our build script :smile: with a JDK and the `sbt` binary, scala projects can bootstrap themselves using the Ivy dependency management system (and we cache the hell out of that).

Emacs is for running the emacs-lisp unit tests in batch mode.

**Comment by fommil** [comment]
http://www.scala-sbt.org/

**Comment by FeodorFitsner** [comment]
Oh, will take a look. Scala is all new stuff for me though I have some Java experience :)

**Comment by fommil** [comment]
@FeodorFitsner from a CI perspective, they are effectively the same. Think about `sbt` like maven... it shoves a bunch of jars into the `~/.ivy2` directory (and also `C:\sbt` --- it bootstraps itself and compiles an interface layer for each crossversion of JDK/Scala).

**Pull request merged**
