### PR TITLE
Add EnsimeProject for .ensime v2 format

### PR DESCRIPTION
**Pull request by yyadavalli**
Add case classes for new EnsimeProject.

### CODE REVIEW

**Comment by fommil** [comment]
cool! Btw, I'm adding `:java-sources` to the format in my current dev branch

**Comment by yyadavalli** [comment]
Ok, I will add that too. Hopefully I can start on updating the analyzer sometime next week.

**Comment by yyadavalli** [comment]
@fommil just saw that `:java-sources` is at a project level i.e. in `EnsimeConfig`
shouldn't it be at the subproject level in `EnsimeProject` along with the scala sources?

**Comment by fommil** [comment]
Nope, java sources are for the whole build, not per project.

**Comment by yyadavalli** [comment]
Hmm, I am a little confused. I thought it is for java sources similar to scala sources.
Is `java-sources` intended to be a different/replacement key for `reference-source-roots` in `.ensime`?
Can I simply rename `referenceSourceRoots`?

**Comment by fommil** [comment]
Yup just a rename. 

Scala is optional per project, java is universal.

**Comment by yyadavalli** [comment]
@fommil Can you please review this, its only a minor addition of case classes

**Comment by fommil** [comment]
will do! Sorry I've been super busy

**Comment by fommil** [comment]
sorry for taking so long, it was easy to review :smile:

**Comment by yyadavalli** [comment]
No problem. Thanks

**Pull request merged**
