### PR TITLE
WIP: a better "organize imports"

### PR DESCRIPTION
**Pull request by lukasz-golebiewski**
WIP

### CODE REVIEW

**Comment by fommil** [comment]
@lukasz-golebiewski we can pick this up at the London Hack Day unless you want to finish it off?

**Comment by lukasz-golebiewski** [comment]
@fommil Thx, but I'd rather finish it off next week - unless it's super urgent ;-)

**Comment by fommil** [comment]
We had other things to look at, it's all yours!

**Comment by fommil** [comment]
this will close #779

**Comment by lukasz-golebiewski** [comment]
I might need some help with this one. Adding the `GroupImports` option results in an error that can be observed when running the newly added test. Is that an error in the `org.scala-refactoring.library`?

```
18:08:52.133 ERROR  o.e.core.RichPresentationCompiler - Error during refactor request: OrganiseImportsRefactorDesc(/tmp/1455556131436-0/testing/empty/src/main/scala/tmp-contents)
scala.MatchError: BlankLine() (of class scala.tools.refactoring.common.PimpedTrees$PlainText$BlankLine$)
        at scala.tools.nsc.ast.Trees$class.xtransform(Trees.scala:161) ~[scala-compiler-2.11.7.jar:na]
        at scala.tools.nsc.Global.xtransform(Global.scala:39) ~[scala-compiler-2.11.7.jar:na]
        at scala.tools.nsc.Global.xtransform(Global.scala:39) ~[scala-compiler-2.11.7.jar:na]
        at scala.reflect.internal.Trees$class.itransform(Trees.scala:1454) ~[scala-reflect-2.11.7.jar:na]
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16) ~[scala-reflect-2.11.7.jar:na]
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16) ~[scala-reflect-2.11.7.jar:na]
        at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555) ~[scala-reflect-2.11.7.jar:na]
        at scala.reflect.internal.Trees$Duplicator.transform(Trees.scala:1676) ~[scala-reflect-2.11.7.jar:na]
        at scala.reflect.internal.Trees$Tree.duplicate(Trees.scala:99) ~[scala-reflect-2.11.7.jar:na]
        at scala.tools.refactoring.implementations.OrganizeImports$Participant$class.stripPositions(OrganizeImports.scala:58) ~[org.scala-refactoring.library_2.11-0.8.0.jar:0.8.0]
        at scala.tools.refactoring.implementations.OrganizeImports$SortImports$.stripPositions(OrganizeImports.scala:122) ~[org.scala-refactoring.library_2.11-0.8.0.jar:0.8.0]
        at scala.tools.refactoring.implementations.OrganizeImports$SortImports$.asText(OrganizeImports.scala:124) ~[org.scala-refactoring.library_2.11        at scala.tools.refactoring.implementations.OrganizeImports$$anonfun$20$$anonfun$apply$3.applyOrElse(OrganizeImports.scala:435) ~[org.scala-refactoring.library_2.11-0.8.0.jar:0.8.0]
        at scala.tools.refactoring.implementations.OrganizeImports$$anonfun$20$$anonfun$apply$3.applyOrElse(OrganizeImports.scala:433) ~[org.scala-refactoring.library_2.11-0.8.0.jar:0.8.0]
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:223) ~[scala-library-2.11.7.jar:na]
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:219) ~[scala-library-2.11.7.jar:na]
        at scala.tools.refactoring.transformation.Transformations$$anon$1.apply(Transformations.scala:67) ~[org.scala-refactoring.library_2.11-0.8.0.jar:0.8.0]
        at scala.tools.refactoring.transformation.Transformations$$anon$1.apply(Transformations.scala:66) ~[org.scala-refactoring.library_2.11-0.8.0.jar:0.8.0]
        at scala.Option.flatMap(Option.scala:171) ~[scala-library-2.11.7.jar:na]
        at scala.tools.refactoring.transformation.Transformations$Transformation$$anon$7.apply(Transformations.scala:42) ~[org.scala-refactoring.library_2.11-0.8.0.jar:0.8.0]
        at scala.tools.refactoring.transformation.Transformations$Transformation$$anon$5.apply(Transformations.scala:49) ~[org.scala-refactoring.library_2.11-0.8.0.jar:0.8.0]
        at scala.tools.refactoring.Refactoring$class.transformFile(Refactoring.scala:41) ~[org.scala-refactoring.library_2.11-0.8.0.jar:0.8.0]
        at scala.tools.refactoring.MultiStageRefactoring.transformFile(MultiStageRefactoring.scala:14) ~[org.scala-refactoring.library_2.11-0.8.0.jar:0.8.0]
        at scala.tools.refactoring.implementations.OrganizeImports.perform(OrganizeImports.scala:439) ~[org.scala-refactoring.library_2.11-0.8.0.jar:0.8.0]
        at scala.tools.refactoring.implementations.OrganizeImports.perform(OrganizeImports.scala:20) ~[org.scala-refactoring.library_2.11-0.8.0.jar:0.8.0]

        at org.ensime.core.RefactoringEnvironment.performRefactoring(Refactoring.scala:39) ~[classes/:na]
        at org.ensime.core.RefactoringImpl$$anon$11.<init>(Refactoring.scala:239) ~[classes/:na]
        at org.ensime.core.RefactoringImpl$class.doOrganizeImports(Refactoring.scala:227) ~[classes/:na]
        at org.ensime.core.RichPresentationCompiler.doOrganizeImports(RichPresentationCompiler.scala:251) [classes/:na]
        at org.ensime.core.RefactoringImpl$class.prepareRefactor(Refactoring.scala:285) ~[classes/:na]
        at org.ensime.core.RichPresentationCompiler.prepareRefactor(RichPresentationCompiler.scala:251) [classes/:na]
        at org.ensime.core.RefactoringControl$$anonfun$askPrepareRefactor$1.apply(Refactoring.scala:156) [classes/:na]
        at org.ensime.core.RefactoringControl$$anonfun$askPrepareRefactor$1.apply(Refactoring.scala:156) [classes/:na]
        at scala.tools.nsc.util.InterruptReq.execute(InterruptReq.scala:26) [scala-compiler-2.11.7.jar:na]
        at scala.tools.nsc.interactive.Global$$anonfun$pollForWork$1.apply$mcV$sp(Global.scala:455) [scala-compiler-2.11.7.jar:na]
        at scala.util.control.Breaks.breakable(Breaks.scala:38) [scala-library-2.11.7.jar:na]
        at scala.tools.nsc.interactive.Global.pollForWork(Global.scala:429) [scala-compiler-2.11.7.jar:na]
        at scala.tools.nsc.interactive.PresentationCompilerThread.run(PresentationCompilerThread.scala:22) [scala-compiler-2.11.7.jar:na]
```

**Comment by fommil** [comment]
@mlangc have you seen this error before?

**Comment by mlangc** [comment]
I have not seen this error before, but I'll look at it more closely tomorrow in the evening.

**Comment by mlangc** [comment]
Hmm, I've just tried to reproduce this in isolation, but the tests pass (at least with HEAD):
https://github.com/mlangc/scala-refactoring/commit/bfd9fea7ffaa35551e4526c1b8811888be5ffaf1

Note that the order of the options matter - you should place `GroupImports` at the end if I'm not mistaken (otherwise the grouping might be broken by subsequent transformations); the stack trace suggests that the error happens in `SortImports`. Does removing this option help? If not try removing other options until the test passes.

**Comment by lukasz-golebiewski** [comment]
@mlangc I tried that already - the error does not occur and the refactoring returns a diff ONLY when I remove the `GroupImports` option

**Comment by mlangc** [comment]
@lukasz-golebiewski So moving `GroupImports` to the very end of the list does not help? Are you using Scala-2.10 or Scala-2.11? Also, can you try with a build from the current master (simply clone https://github.com/scala-ide/scala-refactoring and run `sbt +publishLocal` to add the latest snapshots for Scala-2.10 and Scala-2.11 to you local repo)?

**Comment by fommil** [comment]
@mlangc do you publish snapshots to sonatype? Because we can actually depend on them in our CI if you promise to only push green code :stuck_out_tongue:

**Comment by fommil** [comment]
@mlangc to answer your question, we test on 2.10 and 2.11.

**Comment by lukasz-golebiewski** [comment]
@mlangc: Actually it did help! The CI should be green now, thanks!

**Comment by lukasz-golebiewski** [comment]
@mlangc It didn't occur to me that `GroupImports` should be moved to the end of the options list, I was simply commenting other options out to see what's causing the trouble. Thanks for the hint again.

**Comment by mlangc** [comment]
@fommil As for the snapshots: They are not published for the moment, but that's definitely something to think about!

@lukasz-golebiewski The grouping should really be done at the end - as other transformations might reorder already grouped imports otherwise. I still don't like this exception you encountered though... I'll look into this.

**Comment by fommil** [comment]
@mlang you've got a really simple sbt build, it could easily be snapshot published. You'll just need the credentials on the build machine. Consider copying the `SensibleSettings.scala` and `SonatypeSupport.scala` files from `ensime-server`. Not sure why you bother with cross builds because you can specify this in the build matrix which solves it trivially... and I'd personally just rename the scala version-specific files into the standard naming convention (which is handled by default in recent sbt).

Where does your CI run? We'd be happy to use our drone servers for pull requests and master pushes... I could get somebody to put in the credentials through our web interface if they are happy doing that.

**Comment by mlangc** [comment]
I don't have access to our CI server, but maybe @sschaef or @wpopielarski can comment on this?

**Comment by fommil** [comment]
@mlangc you don't need it, to run it off our drone farm, somebody with publishing rights to the maven `groupId` just needs to encrypt their username/password with the drone public key and add that to the repo (this is what all ensime projects do).

**Comment by mlangc** [comment]
@fommil I fear I don't have this publishing rights either... however, I think that we really should have recent snapshots somewhere for public consumption! Let's see what @sschaef, @wpopielarski or @dragos have to say about this.

**Comment by fommil** [comment]
happy to do the scalariform build as well (and also for hardware contributions... just needs a docker connection and it all works by magic)

**Comment by sschaef** [comment]
Snapshots of scala-refactoring are published to http://download.scala-ide.org/scala-refactoring-lib/
The ones for scalariform are at http://download.scala-ide.org/scalariform-lib/
We don't publish to sonatype since no one needed it so far.

**Comment by fommil** [comment]
we'd need it on sonatype for ensime snapshots (otherwise users need to add another repo, and that's a massive hassle because it means updating multiple codebases and new releases, etc)

**Comment by sschaef** [comment]
Alright, noticed. Will publish to sonatype then soon.

**Comment by fommil** [comment]
I think I've fixed our CI farm now, so restarting the drone builds.

**Comment by fommil** [comment]
niiiiice :smile:

**Comment by lukasz-golebiewski** [comment]
Thanks for that!

**Comment by andrebeat** [comment]
This is great! :+1: The original issue (#779) suggested differentiating between middleware and project imports which this doesn't implement. Do you think it would make sense to expose the groupings as a project setting, or to at least add a new grouping for the project's organization?

**Comment by fommil** [comment]
that'd be pretty funky. We'd have to add a new field to the `.ensime` file, but that's all doable.

Create a ticket and I can help walk you through what would be needed. Start by adding a new field into `config.scala`.

**Comment by fommil** [comment]
oh, I guess we could even infer the project's grouping from the current file so might not even need config file changes.

**Pull request merged**
