### PR TITLE
require java 8 as a minimum

### LINKED ISSUE #1636: Upgrade to Java 8
no objections, but we should probably update the ensime-sbt docs with instructions on how to customise the java version.

### PR DESCRIPTION
**Pull request by fommil**
close #1636

### CODE REVIEW

**Comment by fommil** [comment]
emacs failure

```
Assertion failed at 'Test inspector ui.': (ensime-test-assert-failed . Expected truth of (let ((url (ensime--inspector-doc-url-at-point))) (s-ends-with-p java/lang/String.html#equalsIgnoreCase(java.lang.String) (url-unhex-string url))).)
Error executing test: (ensime-test-interrupted . Test interrupted: (ensime-test-assert-failed . Expected truth of (let ((url (ensime--inspector-doc-url-at-point))) (s-ends-with-p java/lang/String.html#equalsIgnoreCase(java.lang.String) (url-unhex-string url))).).)
```

**Comment by fommil** [comment]
@bwmcadams might have some ideas on these things that are filling up our CI logs...

```
[DEBUG] [11/05/2016 13:02:17.251] [default-akka.actor.default-dispatcher-16] [akka://default/user] stopped
[DEBUG] [11/05/2016 13:02:17.251] [default-akka.actor.default-dispatcher-16] [akka://default/system] received AutoReceiveMessage Envelope(Terminated(Actor[akka://default/user]),Actor[akka://default/user])
[DEBUG] [11/05/2016 13:02:17.251] [default-akka.actor.default-dispatcher-16] [EventStream] shutting down: StandardOutLogger started
```

**Comment by fommil** [comment]
oh, for goodness sake... akka is not available for scala 2.10. They really don't like build matrices, do they? I'll back out the akka upgrade.

**Comment by fommil** [comment]
hmm, windows is timing out. I wonder if we need to bump the heap size to account for permgen => meta changes.

**Comment by fommil** [comment]
hmm, maybe we need class-monkey now because of changes to the way classloaders are GCd.

**Comment by fommil** [comment]
interesting, it's getting stuck at simulating a compile (copy one dir to another). I wonder if the nio filewatcher backend impl changed on windows.

**Comment by fommil** [comment]
might need to take a heap dump when a delete/copy fails https://blogs.oracle.com/sundararajan/entry/programmatically_dumping_heap_from_java

**Comment by fommil** [comment]
the folders themselves seem to be difficult to delete

```
failed to delete C:\Users\appveyor\AppData\Local\Temp\1\1478436533754-0\testing\timing\target\scala-2.11\classes
failed to delete C:\Users\appveyor\AppData\Local\Temp\1\1478436533754-0\testing\timing\target\scala-2.11
```

**Comment by fommil** [comment]
I wonder if this is maybe just a bug in apache FileUtils. I'd certainly like to remove it as a dep in any case.

**Comment by sugakandrey** [comment]
yay!

**Comment by fommil** [comment]
damn, forgot to make and attach the openjdk8 langtools sources

**Pull request merged**
