### PR TITLE
Dummy TODO and FIXME to test CI

### PR DESCRIPTION
**Pull request by asznajder**
We're going to test whether #1400 works fine and PRs with TODO / FIXME will be blocked by CI. That's why, this PR contains both forbidden terms and it should not pass tests.
 
**This PR should never be merged!**

### CODE REVIEW

**Comment by asznajder** [comment]
"fatal: Unimplemented pathspec magic '!' in ':!.drone.yml'"

What version of git do we have there?

**Comment by asznajder** [comment]
_fatal: Unimplemented pathspec magic '!' in ':!.drone.yml'_

What version of git do we have there? I'm using 2.7.4 and it works fine on my computer.

**Comment by asznajder** [comment]
Probably replacing `:!` with `:(exclude)` would work.

**Comment by fommil** [comment]
the `git grep` line does look a it unusual. There is a flag to include all the default files so no need for the wildcard.

**Comment by asznajder** [comment]
I can replace `./*` with `.`, but in my opinion it won't help. I checked in git sources when this message is printed and simply looks like it doesn't know that `!` is `:(exclude)`. I can replace these two things in one shot.

**Comment by fommil** [comment]
I put this on gitter but I guess you missed it:

```
if $(git grep -qE "TODO|FIXME" -- `git ls-files | grep -v .drone.yml`) ; then echo YES ; else echo NO ; fi
```

**Pull request closed without merging**
