### PR TITLE
Post "remove netbeans" refactorings

### PR DESCRIPTION
**Pull request by lukasz-golebiewski**
This PR does not close any ticket. It contains refactorings that came to my head when reviewing "remove netbeans" related code

### CODE REVIEW

**Comment by fommil** [comment]
cool, you're absolutely right. Brain was in "Java mode" when reviewing :smile:

**Comment by lukasz-golebiewski** [comment]
For some reason the appveyor doesn't like the second commit :/

**Comment by rorygraves** [comment]
@lukasz-golebiewski Not you - DebugTest fail.

**Comment by fommil** [comment]
(I'll investigate tonight, it's a real pain)

**Pull request merged**
