### PR TITLE
use stable release of scala-refactoring

### PR DESCRIPTION
**Pull request by fommil**
and only require one LGTM

### CODE REVIEW

**Comment by rorygraves** [comment]
LGTM ;)

**Comment by fommil** [comment]
blocked on http://search.maven.org/#search%7Cga%7C1%7Cscala-refactoring

**Comment by fommil** [comment]
@sschaef can you please make a `_2.10` / `_2.11` style release of `scala-refactoring`?

Also, it needs to work on `2.11.6` because that's what I use at work.

**Comment by fommil** [comment]
note this is blocking #1438 and therefore the 1.0 release.

**Comment by fommil** [comment]
it looks like in https://github.com/scala-ide/scala-refactoring/commit/2128ef75a962d7337c8c678b460192fef7ba9c24 this was done as a workaround to scala publication process, so the 2.11.x jars should all be identical (they aren't actually making releases that depend on the full version).

So we can workaround it by now by basically hardcoding the version of scala-refactoring, but hopefully @sschaef can get back to publishing `binary` cross versions instead of full, as of the next release.

**Comment by fommil** [comment]
LGTM

**Pull request merged**
