### PR TITLE
Scala 2.10

### PR DESCRIPTION
**Pull request by fommil**

### CODE REVIEW

**Comment by fommil** [comment]
wow, there are waaaay more commits than I expected!

**Comment by rorygraves** [comment]
@fommil  - yep, we have all been busy ;), and yes I often disagree with wartremover.

**Comment by fommil** [comment]
Interesting, travis passed but jenkins still isn't set up for the older branches.

I think we can declare the new travis docker instances a success!

**Comment by fommil** [comment]
ha! no I spoke too soon. Looks like the ParserSpec failed with a transient really complex sexpression to parse.

**Pull request merged**
