### PR TITLE
Debounced actors refactor

### PR DESCRIPTION
**Pull request by mwesolowski**
It's my first real attempt to write something in scala so it can be messed up. Proceed with caution.
I wanted to examine how issue 1492 was implemented and as a result this refactor has came up.

### CODE REVIEW

**Comment by fommil** [comment]
cool! I was hoping somebody would clean this up :smile:

Instead of taking in a lambda, how about taking a target actor? (and a delay period, and maybe an option to not debounce the first action)

at you at ScalaX? Come round to the Shift room if so

**Comment by mwesolowski** [comment]
Sure. Does it mean I should also turn SourceResolver into an actor?
No, I'm not at ScalaX. My adventure with Scala just begins. Maybe next year :)

**Comment by fommil** [comment]
that would be a pretty good change if you moved it to be an actor... I think I wrote it before we were using akka.

**Comment by fommil** [comment]
sorry, I missed that you'd updated this! Could you please rebase? I've been ill recently and it slipped my mind. Do not be afraid to ping me every week if I seem to have forgotten.

**Comment by fommil** [comment]
@mwesolowski ping

**Comment by mwesolowski** [comment]
I've rebased but my change is still based on lambdas. I've made some attempts to move SourceResolver into an actor but it still needs some extra workload. I will try to find some time for it next week.

**Comment by fommil** [comment]
@mwesolowski ping, any more thoughts on this one?

**Comment by mwesolowski** [comment]
First I have to get the tests pass locally on my machine (I use macOS Sierra 10.12.4 and sbt 0.13.13). When I run `sbt ++2.11.8 ensimeConfig test` on the clean commit 4e580733 (current HEAD of 2.0) I get the following errors in the tests related to file watchers. Have you ever come across such a case?

SourceResolver is a FileChangeListener itself so I feel quite insecure trying to move this class to be an actor without having working tests in this area. 

```
[info] - should detect added / changed files *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class org.ensime.indexer.Added
```
```
[info] - should detect added / removed files *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class org.ensime.indexer.Added
```
```
[info] - should detect removed base directory *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during fishForMessage, hint:
```
```
[info] - should detect removed parent base directory *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during fishForMessage, hint:
```
```
[info] - should survive deletion of the watched directory *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class org.ensime.indexer.Added
```
```
[info] - should survive removed parent base directory and recreated base *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class org.ensime.indexer.Added
```
```
[info] - should detect changes to a file base *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class org.ensime.indexer.Changed
```
```
[info] - should detect removal of a file base *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class org.ensime.indexer.Removed
```
```
[info] - should be able to start up from a non-existent base file *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class org.ensime.indexer.Added
```
```
[info] - should survive removal of a file base *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class org.ensime.indexer.Removed
```

**Comment by fommil** [comment]
If you're on Mac you can ignore FileWatcherSpec. But integration tests are more important.

**Comment by timcharper** [comment]
Any reason to not use akka streams? Akka streams has some nice components to use for debouncing.

**Comment by iravid** [comment]
Heartily agree on akka-streams but Sam seems to be set on FS2 :-)

**Comment by fommil** [comment]
Akka is too big and has been the biggest problem for us maintaining crossbuild matrices. We have many ensime users who also contribute to fs2.

**Comment by timcharper** [comment]
@fommil I propose we use the following, non-akka specific implementation of Debouncer:

https://gist.github.com/timcharper/51b4a6c4a5291cdfe7970e3f855b2a7c

It has several performance advantages:

- Debounced attempts are filtered synchronously, rather than asynchronously; this means significantly less overhead for the ExecutionContext. Implementation uses AtomicBoolean to guarantee that an invocation will happen after each `call()` attempt.
- It has significantly less interactions with the scheduler. Akka's scheduler instantiates a new TaskHolder instance for each `scheduleOnce` call, and puts it in the queue. Worth noting, the `cancel()` method for the `scheduleOnce` returned cancellable only marks the task as cancelled. This means that the scheduler will still attempt to call every scheduled task.
- Supports a `maxDelay` parameter, which will ensure that the debounced function will be called in the event that events are getting called frequently.
- Less dependency on Akka. Scheduler implementation can be easily swapped out.

**Comment by timcharper** [comment]
@mwesolowski I pushed up a new version of this pull request; I set you as the author, with me as the committer, so we both get credit for the change.

I wanted debouncing to happen _before_ we sent it to the actor, as otherwise it generates a lot of log messages. Also, the above ^

See #1773 

Are you okay with this? @fommil is this kosher with you?

If preferred, we can just merge your patch, @mwesolowski , and then I can rebase mine on top, too. Whatever you prefer.

**Comment by timcharper** [comment]
Doh. I just saw in the history that you requested it be moved to an actor, and before it _was_ not an actor (and took a Lambda).

Perhaps we can discuss tomorrow :)

**Comment by fommil** [comment]
closing in preference of #1773

**Pull request closed without merging**
