### PR TITLE
allows index and exiting

### LINKED ISSUE #1551: Project actor init should happen on creation, not on connection info request
We're delaying indexing until the connection is made, but this means we can't make use of the `ensime.exitAfterIndex` feature.

@rorygraves thoughts? Any reason you can think of why we only init on a connection?

### PR DESCRIPTION
**Pull request by fommil**
close #1551

### CODE REVIEW

**Comment by fommil** [comment]
`org.ensime.server.ServerStartupSpec` is definitely flakey now

**Comment by sugakandrey** [comment]
I'll have to take a look at `ServerStartupSpec` after I'm done with priority tickets, since it was probably me, who introduced this and it is not supposed to be flakey at all.

**Comment by fommil** [comment]
@sugakandrey I've not seen it be flaky anywhere except in this PR, so almost certainly me

**Comment by sugakandrey** [comment]
@fommil alright then, ping me if it comes up somewhere else

**Pull request merged**
