### PR TITLE
do not recreate InputStreamReaders as they can potentially buffer the

### PR DESCRIPTION
**Pull request by fommil**
underlying stream, as discussed in
https://github.com/ensime/ensime-emacs/pull/206

### CODE REVIEW

**Comment by aemoncannon** [comment]
lgtm

**Comment by rorygraves** [comment]
@fommil  Has this broken the integration tests - slightly confused because AFAIK we don't do message encoding and decoding.

**Comment by fommil** [comment]
@rorygraves looks like a weird transient **sigh**

**Comment by rorygraves** [comment]
Its your search one about Random vs Random$

**Comment by fommil** [comment]
oh, and appveyor seems to depend on the hardware they give us. Maybe the timeouts need bumped again.

**Comment by fommil** [comment]
@rorygraves that plus debugtest timeout, and linux failed for some unknown reason.

**Comment by rorygraves** [comment]
More transient errors:
```
[info] - should open the test project *** FAILED ***
[info]   Vector(ClearAllScalaNotesEvent, ClearAllScalaNotesEvent) did not contain only (ClearAllScalaNotesEvent, FullTypeCheckCompleteEvent) (BasicWorkflow.scala:148)
[info]   org.scalatest.exceptions.TestFailedException:
```
It takes two messages expecting 1x ClearAllScalaNotes and 1x FullTypeCheckCompleteEvent - I wonder what causes it to see 2x ClearAllScalaNotes (PC restart??)

**Comment by fommil** [comment]
ok, now linux tests pass.... but we think there is still a problem with the protocol. For outbound messages, the prefix number means the number of bytes, but for inbound it means the number of UTF-8 chars. The correct fix sounds like it should be number of bytes in both directions.

**Comment by aemoncannon** [comment]
Nice catch on the bytes vs chars.

**Pull request merged**
