### PR TITLE
Bump protocol for changes in a71407d3.

### PR DESCRIPTION
**Pull request by aemoncannon**
Need this so we can check version in client and send sourcefileinfo.

### CODE REVIEW

**Comment by fommil** [comment]
hmm, that merge was a little premature, I should have asked for some documentation in `swank/CHANGELOG.md`

**Comment by aemoncannon** [comment]
Ah. Damn. I will follow up.

**Comment by fommil** [comment]
nah, don't bother... just stick it in a commit with your next PR :smile:

Sorry, I've not had time to look at the Java one, I've been swamped with work and talk prep. I'll get to it over the coming weeks.

**Comment by aemoncannon** [comment]
No worries. I actually want to look at our CI w.r.t jvm version coverage.
Do you think it's feasible to run the integrations vs 1.6,1.7,1.8? I think
it's the version of tools.jar that is causing pain.

**Comment by fommil** [comment]
Yup! You'd need to install the jdks in the docker image (1.X branch in ensime-docker). Comments there, because I thought we'd do this post 1.0.

Tests will probably fail on non-JDK6 runs because of bytecode changes resulting in search priority changes.

You *could* just disable some tests on jdk6 and promise me they pass :-)

**Pull request merged**
