### PR TITLE
Switch from scalariform to scalafmt

### PR DESCRIPTION
**Pull request by fommil**
(also to test the new CI)

@olafurpg .... finally, right?

### CODE REVIEW

**Comment by fommil** [comment]
@jozi-k many apologies, this is probably going to cause you a headache when rebasing your PR for 3.0. I split out the commits so that you can see how to enable the formatting on any branch and create a fresh diff.

**Comment by olafurpg** [comment]
😸 
screen shot 2017-09-26 at 11 24 56

**Comment by olafurpg** [comment]
🎉

**Comment by fommil** [comment]
I should probably raise a similar PR against the 2.0 branch to make backporting / forward porting bugfixes / features easier.

**Comment by fommil** [comment]
nah, I'm not maintainer anymore, I'll create a ticket!

**Pull request merged**
