### PR TITLE
fix build

### PR DESCRIPTION
**Pull request by fommil**
partially address #1673 and upgrade some middleware

### CODE REVIEW

**Comment by fommil** [comment]
Looks like I really need to fix the flaky server start test (and fix the formatting of the stack dump)

**Comment by sugakandrey** [comment]
Looks like you got the exact same error I was getting on graph build. `FileWatcherSpec` doesn't like Windows much, in particular `  it should "survive deletion of the watched directory" ` seems to be hanging.

**Comment by fommil** [comment]
argh

**Comment by fommil** [comment]
well, since that's not a problem with this PR... I'll merge and we can deal with it later

**Pull request merged**
