### PR TITLE
Websockets

### LINKED ISSUE #990: Support for Jerk over HTTP
Having the JSON API available as a REST service over HTTP would practically minimize any barriers to writing external tools which talk to Ensime, without learning anything new or proprietary.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/21572141-support-for-jerk-over-http?utm_campaign=plugin&utm_content=tracker%2F239449&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F239449&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by fommil**
closes #990 #1006 and #1045

phew!

### CODE REVIEW

**Comment by fommil** [comment]
grr, curse your infernal reformattings @rorygraves !

**Comment by rorygraves** [comment]
If you can't stand the heat stay out the kitchen...

**Comment by rorygraves** [comment]
Cool stuff.

**Comment by fommil** [comment]
@hedefalk can you please check that you're ok with the changes to JERK? BTW, we're calling the WebSockets variant "JERKY" :smile: 

@propensive what do you want to implement first? Happy to help. Best place to start are the files `WebServer.scala`, `incoming.scala`, `outgoing.scala` and `JerkFormatsSpec.scala`. Also probably the launch script from `ensime-atom` or `ensime-sublime`.

**Comment by rorygraves** [comment]
LGTM

**Pull request merged**
