### PR TITLE
build stability on Travis

### PR DESCRIPTION
**Pull request by fommil**
also, rely on coveralls to tell us if the coverage failed or not (the thresholds are now options)

### CODE REVIEW

**Comment by fommil** [comment]
@rorygraves I've tried lots of different combinations, but for some reason the `DebugTest` keeps timing out when travis runs the coverage. No idea why, maybe a memory limit thing?

**Comment by rorygraves** [comment]
Yeah, I don't think they are stupidly big instances, ensime and debug instance probably push the limits.
will double check by beating the jenkins instance around so they run there properly and see what happens.

**Comment by fommil** [comment]
@rorygraves probably just running locally with different memory settings is a fine tests, but I'm not even sure that's the problem.

**Comment by rorygraves** [comment]
I more mean the entire VM  rather than the processes  - will ahve a play.

**Comment by fommil** [comment]
I disabled the jenkins hooks because they were red lighting on everything.

**Comment by rorygraves** [comment]
I believe that was because the scoverage output location moved - will fix.

**Comment by fommil** [comment]
the multi-module changed the script that needs to be run

**Pull request merged**
