### PR TITLE
Handle exceptions thrown by asm

### PR DESCRIPTION
**Pull request by mberndt123**
“Backport” (it actually applied cleanly) of my recent fix on the 3.0 branch.

### CODE REVIEW

**Comment by mberndt123** [comment]
Apparently something went wrong with some CI jobs, appveyor and drone. Is there a way to retrigger them?

**Comment by yyadavalli** [comment]
The appveyor build ran fine but the status was not reported. https://ci.appveyor.com/project/fommil/ensime-server-circ6/build/1.0.1841

I will check why later.

@mberndt123 if you and @timcharper  are ready to merge it, I can force merge it.

**Comment by mberndt123** [comment]
I'm fine with merging it.

**Comment by mberndt123** [comment]
@yyadavalli , are you going to merge this? And is there going to be a new release of ensime-server 2.0?

**Comment by timcharper** [comment]
I'd suggest we force merge it; @yyadavalli can we temporarily loosen the restrictions for appveyor etc? There are multiple known issues that are being blocked by this.

**Pull request merged**
