### PR TITLE
Middleware

### PR DESCRIPTION
**Pull request by fommil**

### CODE REVIEW

**Comment by fommil** [comment]
last commit is a stylistic change, any strong preference one way or t'other will likely win.

**Comment by fommil** [comment]
2.10.4 failing (might be a transient)
```
 BasicWorkflow:
[info] Server
[info] - should open the test project *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (10 minutes) while expecting 3 messages (got 1)
[info]   at scala.Predef$.assert(Predef.scala:179)
```

**Comment by rorygraves** [comment]
I'm ok with the File changes then.  Overall I good with all the changes, do you need to do any more with Drone before we merge?

**Comment by fommil** [comment]
Yeah, I'm going to fix the 2.10, didn't check locally.

**Pull request merged**
