### PR TITLE
(no-op) rename some modules

### PR DESCRIPTION
**Pull request by fommil**
when on the gitter chat room last night, @magnusart pointed out some "interesting" interpretations of what these packages mean in Swedish (hint: not kid safe!) So renaming just to be on the safe side :grin:

### CODE REVIEW

**Comment by aemoncannon** [comment]
classin' it up.

**Comment by fommil** [comment]
classy bender

**Comment by magnusart** [comment]
Haha, I wouldn't be too concerned about the naming. Using Ensime implicitly means you're with grownups right?

**Comment by fommil** [comment]
not necessarily, I know friends and colleagues who teach high school kids with Emacs and they want to use ENSIME to show some scala.

**Comment by magnusart** [comment]
Fair enough. :)

**Pull request merged**
