### PR TITLE
Simplify ClassName, by using lazy val..

### PR DESCRIPTION
**Pull request by dwijnand**
Not sure why we didn't pursue this avenue..

-11 lines of code look good to me, WDTY?

### CODE REVIEW

**Comment by rorygraves** [comment]
Looks good to me too

**Comment by fommil** [comment]
This does seem simpler than the other alternatives. Nice one.

**Comment by dwijnand** [comment]
Updated. Merge-squash away!

**Comment by fommil** [comment]
what? No GPG verification?

**Pull request merged**
