### PR TITLE
Add debounce to SourceResolver

### PR DESCRIPTION
**Pull request by chiangqiqi**
This PR is to solve incrementally update the sources map in SourceResolver #1492.

### CODE REVIEW

**Comment by fommil** [comment]
btw if you write close #1492 then it gets closed automatically.

**Comment by fommil** [comment]
oh, and I think this means we should be able to remove source and binary watching hacks.

**Comment by fommil** [comment]
I'm not sure where you're based but if you're anywhere near EU, AU or USA, we can send you some ensime stickers to say thank you!

**Comment by chiangqiqi** [comment]
close #1492

**Pull request merged**
