### PR TITLE
Use a monadic fold to limit concurrency in initial indexing

### PR DESCRIPTION
**Pull request by iravid**
Resolves (partially) #1756.

### CODE REVIEW

**Comment by iravid** [comment]
The concurrency limit is performed by limiting the amount of bases indexed. I think it's possible (with some slight refactoring) to limit this on the `SourceSymbolInfo` level if needed.

**Comment by fommil** [comment]
The concurrency is already limited by the config file to 2 threads and one of the workarounds is to set it to 1 thread so I'm not sure this buys us anything. Did you notice any appreciable difference. That blocking queue is really the best way to go for now...

**Comment by iravid** [comment]
Thanks for pointing that out! I wasn’t aware. I haven’t noticed any difference because I haven’t had a problem before :-)

Wouldn’t you say that a blocking queue and a concurrency limit imposed by the threadpool are equivalent?

Also, if the concurrency is already effectively limited, do you know what’s hogging up the heap? If it’s the jars being parsed, we can do that on the threadpool as well, rather than only inserting into Lucene and Orient on the threadpool.



________________________________

**Comment by iravid** [comment]
No, sorry, I see that the symbol extraction is also done on the threadpool.

So @fommil would appreciate any pointers here. I'd be happy to introduce the BlockingQueue.

**Comment by fommil** [comment]
Limiting the concurrency is definitely not the same as a blocking queue because the writing to disk is done by the orientdb so there is no backpressure back to indexing and it can grow to the full set of things to be indexed (whether 1 or a 1000 threads)

**Comment by iravid** [comment]
So, having gone through this again, I found a bug in the previous implementation and having fixed it I believe this now does the Right Thing(tm).

I added some tracing to the `persist` method using an AtomicLong to track how many bases are concurrently indexed:
```
diff --git a/core/src/main/scala/org/ensime/indexer/SearchService.scala b/core/src/main/scala/org/ensime/indexer/SearchService.scala
index 5784968f..ca7e8b22 100644
--- a/core/src/main/scala/org/ensime/indexer/SearchService.scala
+++ b/core/src/main/scala/org/ensime/indexer/SearchService.scala
@@ -3,7 +3,10 @@
 package org.ensime.indexer

 import java.net.URI
+import java.util.concurrent.atomic.AtomicLong
+
 import org.ensime.util.Debouncer
+
 import scala.concurrent._
 import scala.concurrent.duration._
 import scala.util.{ Failure, Properties, Success }
@@ -210,13 +213,19 @@ class SearchService(

   def refreshResolver(): Unit = resolver.update()

+  private val indexingCounter: AtomicLong = new AtomicLong(0)
+
   def persist(symbols: List[SourceSymbolInfo], commitIndex: Boolean, boost: Boolean): Future[Int] = {
+    log.debug(s"Persisting symbols; currenly persisting ${indexingCounter.incrementAndGet()} bases")
     val iwork = index.persist(symbols, commitIndex, boost)
     val dwork = db.persist(symbols)

     for {
       _ <- iwork
       inserts <- dwork
+      _ = {
+        log.debug(s"Done persisting symbols; currently persisting ${indexingCounter.decrementAndGet()}")
+      }
     } yield inserts
   }
```

This is the log from the implementation in the `2.0` branch - it quickly reaches high numbers (and crosses 100 later on):
```
22:07:45.966 DEBUG None o.e.i.SearchService - Done persisting symbols; currently persisting 40
22:07:45.966 DEBUG None o.e.i.SearchService - finished indexing file:///Users/iravid/.ivy2/cache/com.github.fommil.netlib/netlib-native_ref-osx-x86_64/jars/netlib-native_ref-osx-x86_64-1.1-natives.jar
22:07:48.901 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 41 bases
22:07:48.901 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/org.roaringbitmap/RoaringBitmap/bundles/RoaringBitmap-0.5.11.jar
22:07:49.654 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 42 bases
22:07:49.654 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/com.github.rwl/jtransforms/jars/jtransforms-2.4.0.jar
22:07:50.711 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 43 bases
22:07:51.009 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 44 bases
22:07:51.016 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/com.fasterxml.jackson.core/jackson-databind/bundles/jackson-databind-2.8.7.jar
22:07:52.598 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/org.apache.hadoop/hadoop-auth/jars/hadoop-auth-2.2.0.jar
22:07:52.598 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 45 bases
22:07:52.670 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 46 bases
22:07:52.670 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/org.scala-stm/scala-stm_2.11/jars/scala-stm_2.11-0.7.jar
22:07:59.113 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 47 bases
22:07:59.131 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/org.spark-project.spark/unused/jars/unused-1.0.0.jar
22:07:59.147 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 48 bases
22:07:59.157 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/com.amazonaws/aws-java-sdk-core/jars/aws-java-sdk-core-1.10.75.1.jar
22:08:00.019 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 49 bases
22:08:00.019 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/net.sf.py4j/py4j/jars/py4j-0.10.4.jar
22:08:00.238 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/org.apache.zookeeper/zookeeper/jars/zookeeper-3.4.5.jar
22:08:00.240 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 50 bases
22:08:00.371 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 51 bases
22:08:00.371 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.11.jar
22:08:01.524 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 52 bases
22:08:01.527 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.6.jar
22:08:02.935 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 53 bases
22:08:02.935 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/io.netty/netty-all/jars/netty-all-4.0.42.Final.jar
22:08:06.864 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 54 bases
22:08:06.864 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/org.typelevel/machinist_2.11/jars/machinist_2.11-0.6.1.jar
22:08:06.952 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/com.lihaoyi/derive_2.11/jars/derive_2.11-0.4.4.jar
22:08:06.953 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 55 bases
22:08:07.115 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 56 bases
22:08:07.115 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/oro/oro/jars/oro-2.0.8.jar
22:08:07.315 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 57 bases
22:08:07.315 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/org.apache.hadoop/hadoop-mapreduce-client-app/jars/hadoop-mapreduce-client-app-2.2.0.jar
22:08:08.317 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 58 bases
22:08:08.317 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/org.glassfish.jersey.core/jersey-common/jars/jersey-common-2.22.2.jar
22:08:09.500 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 59 bases
22:08:09.500 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/org.apache.hadoop/hadoop-yarn-api/jars/hadoop-yarn-api-2.2.0.jar
22:08:11.367 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 60 bases
22:08:11.367 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/org.apache.spark/spark-sketch_2.11/jars/spark-sketch_2.11-2.1.1.jar
22:08:11.409 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 61 bases
22:08:11.409 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/io.dropwizard.metrics/metrics-jvm/bundles/metrics-jvm-3.1.2.jar
22:08:11.536 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/org.typelevel/cats-kernel-laws_2.11/jars/cats-kernel-laws_2.11-0.9.0.jar
22:08:11.537 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 62 bases
22:08:11.936 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 63 bases
22:08:11.971 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 64 bases
22:08:11.971 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/com.amazonaws/aws-java-sdk-kms/jars/aws-java-sdk-kms-1.10.75.1.jar
22:08:12.328 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 65 bases
22:08:12.334 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/org.apache.ivy/ivy/jars/ivy-2.4.0.jar
```

And this is the log from the implementation in this branch - note that it does not cross 10 at any point:
```
21:59:36.625 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/org.json4s/json4s-core_2.11/jars/json4s-core_2.11-3.2.11.jar
21:59:36.625 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/joda-time/joda-time/jars/joda-time-2.9.4.jar
21:59:37.200 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 1 bases
21:59:37.200 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/org.scala-sbt/test-interface/jars/test-interface-1.0.jar
21:59:37.271 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 2 bases
21:59:37.279 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/org.apache.spark/spark-launcher_2.11/jars/spark-launcher_2.11-2.1.1.jar
21:59:37.378 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 3 bases
21:59:37.378 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/com.lihaoyi/pprint_2.11/jars/pprint_2.11-0.5.2.jar
21:59:37.471 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 4 bases
21:59:37.480 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/org.typelevel/cats_2.11/jars/cats_2.11-0.9.0.jar
21:59:37.485 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/com.esotericsoftware/kryo-shaded/bundles/kryo-shaded-3.0.3.jar
21:59:37.487 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 5 bases
21:59:37.818 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 6 bases
21:59:37.823 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/org.typelevel/cats-core_2.11/jars/cats-core_2.11-0.9.0.jar
21:59:38.001 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 7 bases
21:59:38.001 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/org.apache.commons/commons-crypto/jars/commons-crypto-1.0.0.jar
21:59:38.245 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 8 bases
21:59:38.245 DEBUG None o.e.i.SearchService - indexing file:///Users/iravid/.ivy2/cache/org.slf4j/jcl-over-slf4j/jars/jcl-over-slf4j-1.7.16.jar
21:59:38.261 DEBUG None o.e.i.SearchService - Persisting symbols; currenly persisting 9 bases
21:59:38.429 DEBUG None o.e.i.SearchService - Done persisting symbols; currently persisting 8
21:59:38.429 DEBUG None o.e.i.SearchService - finished indexing file:///Users/iravid/.ivy2/cache/joda-time/joda-time/jars/joda-time-2.9.4.jar
21:59:38.451 DEBUG None o.e.i.SearchService - Done persisting symbols; currently persisting 7
21:59:38.451 DEBUG None o.e.i.SearchService - finished indexing file:///Users/iravid/.ivy2/cache/org.scala-sbt/test-interface/jars/test-interface-1.0.jar
21:59:38.471 DEBUG None o.e.i.SearchService - Done persisting symbols; currently persisting 6
21:59:38.471 DEBUG None o.e.i.SearchService - finished indexing file:///Users/iravid/.ivy2/cache/org.apache.spark/spark-launcher_2.11/jars/spark-launcher_2.11-2.1.1.jar
21:59:38.877 DEBUG None o.e.i.SearchService - Done persisting symbols; currently persisting 5
21:59:38.877 DEBUG None o.e.i.SearchService - finished indexing file:///Users/iravid/.ivy2/cache/org.json4s/json4s-core_2.11/jars/json4s-core_2.11-3.2.11.jar
21:59:38.877 DEBUG None o.e.i.SearchService - Done persisting symbols; currently persisting 4
21:59:38.877 DEBUG None o.e.i.SearchService - finished indexing file:///Users/iravid/.ivy2/cache/org.typelevel/cats_2.11/jars/cats_2.11-0.9.0.jar
21:59:38.987 DEBUG None o.e.i.SearchService - Done persisting symbols; currently persisting 3
21:59:38.987 DEBUG None o.e.i.SearchService - finished indexing file:///Users/iravid/.ivy2/cache/com.lihaoyi/pprint_2.11/jars/pprint_2.11-0.5.2.jar
21:59:39.349 DEBUG None o.e.i.SearchService - Done persisting symbols; currently persisting 2
21:59:39.349 DEBUG None o.e.i.SearchService - finished indexing file:///Users/iravid/.ivy2/cache/com.esotericsoftware/kryo-shaded/bundles/kryo-shaded-3.0.3.jar
21:59:39.386 DEBUG None o.e.i.SearchService - Done persisting symbols; currently persisting 1
21:59:39.386 DEBUG None o.e.i.SearchService - finished indexing file:///Users/iravid/.ivy2/cache/org.apache.commons/commons-crypto/jars/commons-crypto-1.0.0.jar
21:59:39.416 DEBUG None o.e.i.SearchService - Done persisting symbols; currently persisting 0
```

**Comment by fommil** [comment]
Although it will slow things down for me, with my 64GB RAM, this is probably worth it to reduce the heap pressure on most users. Strange that we should be interested in merging a feature that explictly makes our app *less* efficient.

But I'm not sure what you mean by

> I suggest that we remove the explicit threadpool based limiting in extractSymbols... and move the call to persist up into indexBases to make it more clear that we're limiting the concurrency at that point.

Can you please go into more detail?

I'll merge this when it goes green and see what people think.

**Comment by fommil** [comment]
eek. This slows down the tests by quite a bit too... used to take 17 mins but is now taking 25 for each entry in the matrix. Should I wait until you have your follow up? It's still not true backpressure though, is it? It's just slowing down the indexer.

**Comment by iravid** [comment]
Yeah, true backpressure would have the advantage of pipelining; this solution waits for the entire batch of 10 bases to finish before launching another batch.

It’s not surprising that this slows tests down as we are just slowing down the indexer :-) We can make the batch size configurable and increase it in tests to recover the speed there.

Regarding the follow up, I’ll write this up in a separate commit tomorrow and we’ll see how that looks. Thanks for the pointers earlier today!


________________________________

**Comment by fommil** [comment]
btw, I'd be quite happy to merge this if you can add the batch size to the config. It should be pretty simple, add it to `EnsimeServerConfig` then fix all the compile errors, then add the default to `application.conf`.

There are *soooo* many things in the searcher/indexer that should be config parameters.

**Comment by fommil** [comment]
You know what, let's do that batch size in a follow up. This is "unstable" afterall :stuck_out_tongue:

**Comment by fommil** [comment]
@jvican happy holiday present

**Comment by fommil** [comment]
btw, some data points *before* this PR... with default, concurrent mark sweep and g1 (I'll do *after* when it is disted)

ensime-gc
ensime-gc-cms
ensime-gc-g1

**Comment by fommil** [comment]
After (note that CMS doesn't behave very well because it's getting into a full GC loop)

ensime-gc-after
ensime-gc-cms-after
ensime-gc-g1-after

**Comment by fommil** [comment]
it's hardly backpressure, but it does seem to reduce the memory pressure a little.

**Pull request merged**
