### PR TITLE
Add scala keywords to completion results.

### PR DESCRIPTION
**Pull request by tbje**
Simple potential fix for #1009. For discussion.

### CODE REVIEW

**Comment by fommil** [comment]
for reference https://github.com/company-mode/company-mode/commit/9c8364d51f542c0ee9d47806d43bcc13fd7f60a1

Cool, thanks. I think the CI machines are running particularly slowly so I've restarted.

The only concern I would raise is that the completions are not semantic. For example, typing `for` will suggest `forSome` even though you might be in a block. It's not a major deal but it would be really cool if we only suggested keywords that are valid for that point.

**Comment by hedefalk** [comment]
Could we put these things under client-flags? In Atom, I also use a simple language-scala package which provides code-snippets and keywords and stuff like that inside the same autocomplete feature. Basically you register yourself as an "autocomplete provider" and both ensime-atom and language-scala plugins does this. So far I haven't really had any duplication problems, I just put the Ensime result (of max 5) on top, but with this change I think I will get duplicates.

I guess this is a deeper question: should Ensime be a full goto IDE by itselfe or should it play nice with other editors+plugins? I think we can do both if we just put some features under flags, right?

**Comment by fommil** [comment]
yup, all good points and emacs has a similar thing. I'm tempted to say that maybe this should be a client side feature, unless we can do it contextually on the server. @rorygraves ?

**Comment by aemoncannon** [comment]
We have the AST on the server but I'm not sure how expensive it would be to
'localize' the point and figure out what keywords are applicable.

**Comment by rorygraves** [comment]
@hedefalk @fommil This has to be a server side thing for me - two reasons:
1. Everybody gets the same
2. logic improvements (e.g. as @aemoncannon using the ast for region identification) need to AST

Whilst it would be very quick to get working directly pushed into the editor completer to get really good support I think it has to be server side.

**Comment by fommil** [comment]
can you please rebase? I pushed a small change to stabilise the build

**Comment by tbje** [comment]
Providing the "correct" keyword would be great. I also tend to prefer the server side keyword completion as it will give you the out of the box experience. Setting up the right back-end for company-mode etc at least needs to be well documented, also it seems ensime will always provide some completions so the keywords won't show up before you've written a large part of the word (or never for implicit / throw ) if used as a fallback. Rebased and improved.

**Comment by fommil** [comment]
thanks!

**Pull request merged**
